### ISSUE TITLE
AWS::ApiGateway::Account Dependency Note

### ISSUE THREAD

**Issue by JohnONeill** [awsdocs/aws-cloudformation-user-guide#1008]
The documentation under the [`AWS::ApiGateway::Account` resource](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-apigateway-account.md#awsapigatewayaccount) says that "you must add a dependency on another API Gateway resource, such as an AWS::ApiGateway::RestApi or AWS::ApiGateway::ApiKey resource" before creating this resource.

However, from our own testing, it seems like we can successfully create this resource on a fresh account with no dependency on other resources and where no ApiGateway resources have been previously created.

Could someone verify that this is still a required dependency?

Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
