### ISSUE TITLE
Conditions in Outputs is not very well documented

### ISSUE THREAD

**Issue by pplu** [awsdocs/aws-cloudformation-user-guide#1015]
Hi,

Wanting to make a conditional output and browsing the documentation on outputs (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html): the "Outputs fields" section of the documentation fails to mention the "Condition" field. Although it is mentioned a bit later, a quick look at the "outputs fields" section misleads you into thinking that Condition is not supported on an Output.

Suggestion would be to add "Condition" as a field in "Outputs fields"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
