### ISSUE TITLE
AWS::StepFunctions::StateMachine Fn::GetAtt Arn doc might be out of date

### ISSUE THREAD

**Issue by Daniel-Cavallaro** [awsdocs/aws-cloudformation-user-guide#1022]
On the AWS::StepFunctions::StateMachine doc under the Fn::GetAtt section, it has a comment for the Arn property as "Not currently supported by AWS CloudFormation"

I tested this today as an Output on a CloudFormation stack and it reported the correct Arn for the Step Function. Is this now supported by CloudFormation and the docs weren't updated or are there pitfalls we should be wary of?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
