### ISSUE TITLE
Clarification required on AWS::ECS::Service DeploymentConfiguration

### ISSUE THREAD

**Issue by totubamowo** [awsdocs/aws-cloudformation-user-guide#1030]
The documentation under the AWS::ECS::Service DeploymentConfiguration resource says that "if the tasks in the service use the Fargate launch type, the maximum percent & minimum healthy percent value is not used, although it is returned when describing your service".

However, from our own testing, it appears these properties are used during the deployment of our service despite using Fargate launch type.

Could someone confirm the expected behaviour as we rely on the maximum percent & minimum healthy percent values to ensure there is no downtime when deploying our ECS services and want to sure they will be supported with Fargate going forward.

Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
