### ISSUE TITLE
Unable to remove Tags in Resource AWS::CodeDeploy::Application

### ISSUE THREAD

**Issue by jainakhi** [awsdocs/aws-cloudformation-user-guide#1041]
I defined the resource “AWS::CodeDeploy::Application” with tags and later updated the stack by removing them, which gave an error "Update to resource type AWS::CodeDeploy::Application is not supported."

The Docs mentions that the Tag Update will not interrupt anything. [1]
[1] CodeDeploy CloudFormation - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-codedeploy-application.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
