### ISSUE TITLE
Inconsistent documentation around dynamic CF template values

### ISSUE THREAD

**Issue by DKlinec** [awsdocs/aws-cloudformation-user-guide#1050]
There are inconsistencies in the [documentation](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/dynamic-references.md).

Under the "Important considerations when using dynamic parameters for Secrets Manager secrets" section:
The code snippet is:
  `'{{resolve:secretsmanager:MySecret:SecretString:password:EXAMPLE1-90ab-cdef-fedc-ba987EXAMPLE}}'`
(Note the single colon before the version-id)

Further down the text in the example:
"Specifying the following segments would retrieve the password value for the version of the MySecret secret with the version ID of EXAMPLE1-90ab-cdef-fedc-ba987EXAMPLE." 
The code snippet is:
`'{{resolve:secretsmanager:MySecret:SecretString:password::EXAMPLE1-90ab-cdef-fedc-ba987EXAMPLE}}'`
(Note the double colon before the version-id)

I haven't opened a PR since I don't know which one is the correct one. I have issues with both ways, probably because I am trying to !Ref the version-id which I don't know if it's supported. Maybe you can extend the documentation with an example for that:

e.g. this is what I am trying to do:
`'{{resolve:secretsmanager:MySecret:SecretString:password::!Ref SecretVersionIdParameter}}'`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
