### ISSUE TITLE
Incorrect example syntax for "AWS::Events::Connection"

### ISSUE THREAD

**Issue by celkins** [awsdocs/aws-cloudformation-user-guide#1066]
The example in `doc_source/aws-resource-events-connection.md` under the "Create a connection with OAuth authorization parameters" heading has a number of errors:
- `AuthorizationType` should be `OAUTH_CLIENT_CREDENTIALS`.
- `ClientId` in `ClientParameters` should be `ClientID`. See [EventBridge API reference](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateConnectionOAuthClientRequestParameters.html).
- `AdditionalParameters` should be `OAuthHttpParameters` See [EventBridge API reference](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_CreateConnectionOAuthRequestParameters.html).
- `BodyParameters` should be an array of `ConnectionBodyParameter` not an arbitrary mapping of key-value pairs. See [EventBridge API reference](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_ConnectionHttpParameters.html).

(The example under the "Create a connection with ApiKey authorization parameters" heading has a similar issue with its use of `AdditionalParameters`. It is not clear to me what the purpose of the example body parameter is, but in any case that block does not seem to correspond to any available parameter in `CreateConnectionAuthRequestParameters`.)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
