### ISSUE TITLE
Broken image on AWS CloudFormation "Specifying stack name and parameters"

### ISSUE THREAD

**Issue by mvdobrinin** [awsdocs/aws-cloudformation-user-guide#1073]
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-console-create-stack-parameters.html#cfn-using-console-create-stack-parameters-awstypes.

![image](https://user-images.githubusercontent.com/1854768/136297277-3888f13e-40de-45a8-9900-d5b230975dba.png)

The image is broken.

**Comment by HLeeHart** [comment]
Thanks for the report - the image was removed.
