### ISSUE TITLE
Apache Kafka outdated versions

### ISSUE THREAD

**Issue by bdesert** [awsdocs/aws-cloudformation-user-guide#1080]
Apache Kafka versions are outdated: [1.1.1 and 2.2.1](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-msk-cluster.md#:~:text=requires%3A%20No%20interruption-,KafkaVersion,-The%20version%20of).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
