### ISSUE TITLE
BucketAccessRoleArn not properly described for AWS::DataSync::LocationS3 S3Config

### ISSUE THREAD

**Issue by DerkSchooltink** [awsdocs/aws-cloudformation-user-guide#1084]
I ran into this vague description when creating a location in DataSync for an S3 bucket.

> BucketAccessRoleArn
The Amazon S3 bucket to access. This bucket is used as a parameter in the CreateLocationS3 operation.

It implies that you have to reference a bucket ARN for this property, but instead it expects a role ARN that is used by DataSync to access the aforementioned bucket. The name of the property implies this correctly, but the description might throw people off.

This is correctly described in the [Golang SDK for DataSync](https://docs.aws.amazon.com/sdk-for-go/api/service/datasync/#S3Config), but in other documentation pages it is also referenced to as the bucket ARN instead of the role ARN:

1. https://docs.aws.amazon.com/datasync/latest/userguide/API_S3Config.html#DataSync-Type-S3Config-BucketAccessRoleArn 
2. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-datasync-locations3-s3config.html#cfn-datasync-locations3-s3config-bucketaccessrolearn
3. https://awscli.amazonaws.com/v2/documentation/api/latest/reference/datasync/create-location-s3.html

I would propose using the documentation in the Golang SDK and apply it across all documented cases of BucketAccessRoleArn:

> The Amazon Resource Name (ARN) of the Identity and Access Management (IAM) role that is used to access an Amazon S3 bucket.

If this proposal is accepted, I will make an effort to also log issues and submit PR's for the other open-source documentation projects of AWS. 😄

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
