### ISSUE TITLE
AWS::Glue::SecurityConfiguration updates not supported

### ISSUE THREAD

**Issue by rohan-1995** [awsdocs/aws-cloudformation-user-guide#1090]
Hi team, 

It seems like Glue Security Configuration updates are not supported and there is no such API call.  Glue Security Configuration type resources can only be created or deleted. But CloudFormation documentation for this resources suggests update can be performed on this resource's properties.

Please confirm if documentation [1] needs update or API for Glue service to update " Glue Security Configuration" has not been listed in [2]

[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-glue-securityconfiguration.html
[2] https://docs.aws.amazon.com/glue/latest/webapi/API_Operations.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
