### ISSUE TITLE
Location field missing from Cloudformation example for Kinesis Firehose

### ISSUE THREAD

**Issue by ant-theodo** [awsdocs/aws-cloudformation-user-guide#1091]
Hi Folks,

The Cloudformation for the [Convert Record Format](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-kinesisfirehose-deliverystream.md#convert-record-format) example in the Kineses Firehose docs creates a Glue Database and Table but doesn't specify the location of the S3 bucket that the data can be found.

Without the `Location` field Athena will not see the table, and you've effectively created a table with no data. The `Location` field is a property of the `StorageDescripter` property of the `TableInput` property. As per the [Cloudformation docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-table-storagedescriptor.html#cfn-glue-table-storagedescriptor-location) 

Ant

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
