### ISSUE TITLE
MSK connect, plugin, worker missing

### ISSUE THREAD

**Issue by fjbecerra** [awsdocs/aws-cloudformation-user-guide#1097]
Hey,
I haven't seen MSK connect, plugin or worker in the doc, is that because isn't supported yet ? Thanks

**Comment by rachfop** [comment]
Doesn't appear to be supported yet. You can see CloudFormation requests here:
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues?q=is%3Aissue+is%3Aopen+msk
