### ISSUE TITLE
AWS::Cognito::UserPoolUser - Incorrect casing in UserAttributes value and missing documentation on MessageAction behaviour 

### ISSUE THREAD

**Issue by axelra82** [awsdocs/aws-cloudformation-user-guide#1104]
[UserAttributes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpooluser.html#cfn-cognito-userpooluser-userattributes) has incorrect casing for values.

---

### UserAttributes
The user attributes and attribute values to be set for the user to be created. [...]
**email:** The email address of the user to whom the message that contains the code and user name will be sent. Required if the `email_verified` attribute is set to `True` **(this should be `true`)**, or if `"EMAIL"` is specified in the DesiredDeliveryMediums parameter.

---

Found this problem while creating a user for a cognito userpool in CDK.

```
[...]
const createUser = new custom_resources.AwsCustomResource(
      this,
      `${clientName}-cognito-create-user`,
      {
        onCreate: {
          service: "CognitoIdentityServiceProvider",
          action: "adminCreateUser",
          parameters: {
            UserPoolId: userPool.userPoolId,
            Username: owner,
            TemporaryPassword: generatePassword(),
            // Omit the MessageAction to send email
            // MessageAction: "RESEND | SUPPRESS",
            DesiredDeliveryMediums: ["EMAIL"],
            ForceAliasCreation: false,
            UserAttributes: [
              {
                Name: "email",
                Value: owner,
              },
              {
                Name: "email_verified",
                Value: "true", // <-- As per documentation I initially used True here, which didn't apply the value. This has to be true (with a lowercase "t").
              },
            ],
          },
          physicalResourceId: custom_resources.PhysicalResourceId.of(
            `${clientName}-cognito-create-user-${owner}`
          ),
        },
        policy: custom_resources.AwsCustomResourcePolicy.fromSdkCalls({
          resources: custom_resources.AwsCustomResourcePolicy.ANY_RESOURCE,
        }),
      }
    );
[...]
```

Also, notice the comment `// Omit the MessageAction to send email` that I'm saving in there for any future developers working on our project... The documentation only states `"RESEND"` | `"SUPPRESS"`. But `SUPPRESS` means no email is sent for a user that is created with an autogenerated password (not great). And `RESEND` causes the CDK deploy to crash, because it's trying to re-send to an existing user, that is being created (i.e. doesn't exist). So this took some time to get right.

I think it makes sense to make a **NOTE** in the documentation, that omitting the `MessageAction` also has an effect (in our case, the desired one, i.e. sending out a welcome email (with credentials) while creating the user).

---

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-cognito-userpooluser.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
