### ISSUE TITLE
AWS::Glue::Crawler no EventQueueArn property

### ISSUE THREAD

**Issue by jcgutier** [awsdocs/aws-cloudformation-user-guide#1111]
There is a new feature in AWS Glue Crawlers: [Accelerating Crawls Using Amazon S3 Event Notifications](https://docs.aws.amazon.com/glue/latest/dg/crawler-s3-event-notifications.html).

But I can't find a way to implement this on CloudFormation.

The property: **EventQueueArn** is not an allowed parameter under: Targets -> S3Targets on CloudFormation.

**Comment by HLeeHart** [comment]
Thanks for this report. This was corrected.
