### ISSUE TITLE
CloudFormation VPC Creation with IPAM

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#1116]
Hi, 

Could we get more clarity on the required/optional fields and how to use IPAM with Creating a VPC?  Specifically how to use the properties IPv4IpamPoolId, Ipv4NetmaskLength, and CidrBlock.  It seems that some combinations of these do not work when creating a VPC.

Thanks!

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-ec2-vpc.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
