### ISSUE TITLE
AWS::ElastiCache::GlobalReplicationGroup Members

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#1120]
CloudFormation throws an error when trying to create a GlobalReplicationGroup with multiple members.  Could we get more guidance on how to create a GlobalReplicationGroup or if Members only takes 1 member?  By the way the page is written, it seems that Members should take multiple members.  

Error: "GlobalReplicationGroup cannot be created with multiple members."

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
