### ISSUE TITLE
CloudFormation Resource Tag Propogation

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#1121]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html

This page states: "All stack-level tags, including automatically created tags, are propagated to resources that CloudFormation supports. Currently, tags aren't propagated to Amazon EBS volumes that are created from block device mappings."

However, this does not seem to be the case.  For example IAM::ManagedPolicy and other resources.  Could we get more clarity on which resources have tags properly propagated from the stack-level?

**Comment by sopel** [comment]
We struggled with the same question and have inquired about it via our [AWS Partner Network](https://aws.amazon.com/partners/) contact - here's the service team's response (paraphrased):

> We don't have a list of resources that do and don't support tagging.
> However, you can run `describe-type` on a resource and if the `taggable` property is set to true then they support tagging (see https://github.com/aws-cloudformation/cloudformation-resource-schema).

Worth noting that the `taggable`  property is deprecated in favor for the more detailed `tagging` property, but either way this allows to craft a list of resource types that support CloudFormation tag propagation programmatically.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
