### ISSUE TITLE
Clarity question about the "ThrottlingRateLimit" property in the "AWS::ApiGateway::Stage MethodSetting" setting

### ISSUE THREAD

**Issue by ryancabanas** [awsdocs/aws-cloudformation-user-guide#1122]
Hi,

I've been reading the API Gateway documentation regarding throttling and it talks about using a usage plan to accomplish this.  I also see the `ThrottlingRateLimit` property beneath the CloudFormation [AWS::ApiGateway::Stage MethodSetting](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-properties-apigateway-stage-methodsetting.md), though, too.

The [AWS::ApiGateway::Stage MethodSetting](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-properties-apigateway-stage-methodsetting.md) setting description states that it "configures settings for all methods in a **_stage_**", yet the description for the `ThrottlingRateLimit` property says, "The number of steady-state requests per second that API Gateway permits **_across all APIs, stages, and methods in your AWS account_**."

So my question is, does the `ThrottlingRateLimit` property apply only to the given stage, or to "all APIs, stages, and methods in your AWS account"?

Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
