### ISSUE TITLE
AWS::S3::Bucket VersioningConfig redirects to home page

### ISSUE THREAD

**Issue by jacksenk** [awsdocs/aws-cloudformation-user-guide#1140]
Can't visit https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-versioningconfig.html

302 redirects to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-versioningconfiguration.html which redirects to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/

Probably related to renaming `aws-properties-s3-bucket-versioningconfig.md` to `aws-properties-s3-bucket-versioningconfiguration.md` in commit https://github.com/awsdocs/aws-cloudformation-user-guide/commit/ce3d9762108f2d5d55837c1bc28dd53f20eff481/doc_source/aws-properties-s3-bucket-versioningconfiguration.md

**Comment by heyjoahna** [comment]
Similar issue with **AWS::S3::Bucket** resource type reference. 

Can't visit the main page https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html. It redirects to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/Welcome.html.

**Comment by FrederiqueRetsema** [comment]
Same issue with the AWS::S3::Bucket page here.

**Comment by rachfop** [comment]
Thank you. We are looking into this.

**Comment by rachfop** [comment]
The URL `-versioingconfig` is now `-versioningconfiguration`. `aws-resource-s3-bucket` is now up and running. Thank you all for your help identify these links.
