### ISSUE TITLE
Template format error: Unrecognized resource types: [AWS::KinesisVideo::SignalingChannel]

### ISSUE THREAD

**Issue by Ramnirmal0** [awsdocs/aws-cloudformation-user-guide#1144]
### Getting error while creating cloud formation stack : -

Template contains errors.: Template format error: Unrecognized resource types: [AWS::KinesisVideo::SignalingChannel]

**Comment by rachfop** [comment]
Thank you for your submission. This repo is for the CloudFormation docs -- your issue seems to be with a specific resource and not necessarily a doc issue. You may be using a resource in a Region that's not supported, but I'm going to close this issue. Thanks!
