### ISSUE TITLE
[AWS::Batch::JobDefinition] - Update documentation: "Timeout" property missing

### ISSUE THREAD

**Issue by mvinii94** [awsdocs/aws-cloudformation-user-guide#115]
Hi, 

**Documentation:** https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_so... 
**Resource Type:** AWS::Batch::JobDefinition 

It seems that the "AWS::Batch::JobDefinition" resource type already supports the underlying Batch JobDefinition "**Timeout**" [1] property declaration in CloudFormation, but its documentation is not updated. Could you please include it? 

Reference: 

[1] - Timeout: 
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameter... 

=== sample === 
```
Resources:
  JobDefinition:
    Type: 'AWS::Batch::JobDefinition'
    Properties:
      Type: container
      JobDefinitionName: nvidia-smi
      ContainerProperties:
        MountPoints:
          - ReadOnly: false
            SourceVolume: nvidia
            ContainerPath: /usr/local/nvidia
        Volumes:
          - Host:
              SourcePath: /var/lib/nvidia-docker/volumes/nvidia_driver/latest
            Name: nvidia
        Command:
          - nvidia-smi
        Memory: 2000
        Privileged: true
        JobRoleArn: String
        ReadonlyRootFilesystem: true
        Vcpus: 2
        Image: nvidia/cuda
      Timeout:
        AttemptDurationSeconds: 300
```
=== sample ===

Thank you.

**Comment by ckesser** [comment]
@mvinii94 Thanks for bringing attention to this! We've added the 'Timeout' property to the docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-batch-jobdefinition.html#cfn-batch-jobdefinition-timeout. I'm going to close out this issue.

We really appreciate your feedback!
