### ISSUE TITLE
Clarification request: AWS::CloudFront::Distribution DistributionConfig property

### ISSUE THREAD

**Issue by Sleavely** [awsdocs/aws-cloudformation-user-guide#1156]
The `DistributionConfig` property on [AWS::CloudFront::Distribution](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html#aws-resource-cloudfront-distribution-properties) ends its description with an ambiguous phrasing that leaves me unsure whether it is telling me as a reader to send a request or if it is an unfinished explanation of what the property does. Can someone with insight help me understand and possibly adjust it?

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/f4064571678da0f107df958ae168c705380f69c3/doc_source/aws-resource-cloudfront-distribution.md?plain=1#L35

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
