### ISSUE TITLE
CloudFormation Documentation for Security Hub

### ISSUE THREAD

**Issue by jyzhao** [awsdocs/aws-cloudformation-user-guide#1158]
The [CloudFormation documentation for Security Hub](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-securityhub-hub.html) is very limited.
I wonder if there's any doc on how to

1. Enable Security Hub in specified accounts or all accounts for an organization
2. Enable finding aggregation
3. Specify Delegated Administrator by account id

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
