### ISSUE TITLE
AWS::ApiGatewayV2::Stage Clarity for Route Settings

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#1161]
Could we get more clarity around Route Settings and whether this can be set for specific routes?  https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-stage.html#cfn-apigatewayv2-stage-routesettings similar to https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-throttling.html for the specific throttling/settings for a route?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
