### ISSUE TITLE
Enable Unauthenticated access using terraform msk resources 

### ISSUE THREAD

**Issue by Hasinibitla2404** [awsdocs/aws-cloudformation-user-guide#1163]
Hi, i have created the msk cluster using the aws-msk-cluster resource. But after creating the “unauthenticated access” is not enabled. Only the IAM access is enabled. Please tell me how can we enable the “unauthenticated access” using the terraform resource.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
