### ISSUE TITLE
AWS::ApiGateway::DocumentationPart Properties

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#1164]
Hi, on the DocumentationPart Resource, it looks like it has the property, "Properties" but the examples show "Property".  Could we get clarity/adjust the example to match the resource?

Thanks.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-documentationpart.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
