### ISSUE TITLE
FSx resources removed from documentation

### ISSUE THREAD

**Issue by statini4** [awsdocs/aws-cloudformation-user-guide#1187]
A handful of FSx resources were removed from the documentation in "Periodic updates 2022-03-15". Was that intention and these resources are now deprecated/retired or was it a mistake?

[AWS::FSx::Snapshot](aws-resource-fsx-snapshot.md)
[AWS::FSx::StorageVirtualMachine](aws-resource-fsx-storagevirtualmachine.md)
[AWS::FSx::Volume](aws-resource-fsx-volume.md)

**Comment by HLeeHart** [comment]
Thanks for the report. It was a mistake that has been corrected. For example, see
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-snapshot.html
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-fsx-snapshot.md
