### ISSUE TITLE
No Lambda URL

### ISSUE THREAD

**Issue by w0rmr1d3r** [awsdocs/aws-cloudformation-user-guide#1199]
Hello!
Small question:

I believe the documentation for lambda URLs is missing, found it in here -> https://docs.aws.amazon.com/lambda/latest/dg/urls-configuration.html#urls-cfn
But doesn't appear in -> https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/AWS_Lambda.html

Any updates on when this will be published?

Thank you in advance!

**Comment by HLeeHart** [comment]
Sorry for the late response, but this was updated earlier this year.
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-lambda-url.md
