### ISSUE TITLE
Please be clearer on the Parameters property for AWS Glue Table TableInput

### ISSUE THREAD

**Issue by dlabey** [awsdocs/aws-cloudformation-user-guide#120]
It took us a while to figure out "classification" was stored in this property or that we could even put this property here.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
