### ISSUE TITLE
Different order for examples of AWS::EC2::CustomerGateway

### ISSUE THREAD

**Issue by w0rmr1d3r** [awsdocs/aws-cloudformation-user-guide#1206]
Hi 👋 
The examples of `AWS::EC2::CustomerGateway` follow a different order.
It's always JSON then YAML, for the specification and examples, but it has a switched order for the examples in:
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-ec2-customer-gateway.md

Do you want me to open a PR with those changes?

Thank you!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
