### ISSUE TITLE
Missing " in AWS::Route53Resolver::ResolverRule example

### ISSUE THREAD

**Issue by w0rmr1d3r** [awsdocs/aws-cloudformation-user-guide#1207]
AWS::Route53Resolver::ResolverRule is missing a `"` in the JSON example.

Link to the JSON example -> https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-route53resolver-resolverrule.md#json-1
The second IP in `TargetIps` is missing the `"`:
```
      {
        "Ip" : "192.0.2.99,  <-- there
        "Port" : "53"
      }
```

happy to open a PR if needed

**Comment by w0rmr1d3r** [comment]
PR with the fix -> https://github.com/awsdocs/aws-cloudformation-user-guide/pull/1211

**Comment by HLeeHart** [comment]
Thank you for reporting the issue. It has been corrected.
