### ISSUE TITLE
InterfaceType  for AWS::EC2::NetworkInterface isn't clear enough

### ISSUE THREAD

**Issue by w0rmr1d3r** [awsdocs/aws-cloudformation-user-guide#1209]
Hi there 👋 !

The `InterfaceType` for the resource `AWS::EC2::NetworkInterface` isn't clear enough.
The allowed values are `efa` and `trunk`, and the default `interface` but under `Allowed values` it includes `branch`?

The documentation:
```markdown
`InterfaceType`  <a name="cfn-ec2-networkinterface-interfacetype"></a>
The type of network interface\. The default is `interface`\. The supported values are `efa` and `trunk`\.  
*Required*: No  
*Type*: String  
*Allowed values*: `branch | efa | trunk` 
```
from https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-ec2-networkinterface.md

What haven't I understood?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
