### ISSUE TITLE
Typo correction

### ISSUE THREAD

**Issue by RajasGujarathi** [awsdocs/aws-cloudformation-user-guide#1214]
The document [Setting up VPC endpoints for AWS CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-vpce-bucketnames.html) under the section [Before you begin](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-vpce-bucketnames.html#cfn-setting-up-vpc-considerations) mentions 

> If you use CloudFormation to create resources in a VPC with a VPC endpoint, you might need to modify your IAM endpoint policy so that it permits access to certain S3 buckets.

I feel it should be `VPC endpoint policy` instead of `IAM endpoint policy`

Please let me know if my interpretation of the statement is correct ❓

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
