### ISSUE TITLE
Cloudfront Function FunctionConfig is required to deploy

### ISSUE THREAD

**Issue by woodworker** [awsdocs/aws-cloudformation-user-guide#1219]
The documentation states that FunctionConfig is optional/not required but when i want to deploy a function i get a very unhelpful error and a failed deployment

```
Resource handler returned message: "null" (RequestToken: xxx-xxx-xxx-xxx-xxx, HandlerErrorCode: InternalFailure)
````

In https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-cloudfront-function.md it is stated that FunctionConfig is not required is. As there is also the FunctionCode as not required marked is this an dependency?
As in if there is FunctionCode given you also MUST give a FunctionConfig? If yes, this should also be noted in the documentation.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
