### ISSUE TITLE
Contradictory documentation of Fn::ImportValue

### ISSUE THREAD

**Issue by zafodB** [awsdocs/aws-cloudformation-user-guide#1226]
The _Important_ box under [Yaml shorthand declaration](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/intrinsic-function-reference-importvalue.md#yaml-2) warns against using `!ImportValue` together with `Fn::Sub`. However, the example _Yaml - Stack B Import_ just a few lines above does exactly that.

Perhaps the example should be updated to do the import the right way, or the warning in the _Important_ box should be removed.

Example:
![image](https://user-images.githubusercontent.com/18397619/171007344-b0a291e0-782d-47aa-b684-89370f31b99a.png)

_Important_ box:
![image](https://user-images.githubusercontent.com/18397619/171007499-ae561a27-87a2-42eb-925d-574b76607436.png)

**Comment by HLeeHart** [comment]
Thank you for raising the issue. It has been corected.
