### ISSUE TITLE
Contradictory documentation of Alarm MetricDataQuery

### ISSUE THREAD

**Issue by zafodB** [awsdocs/aws-cloudformation-user-guide#1227]
In page [AWS::CloudWatch::Alarm MetricDataQuery](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-properties-cloudwatch-alarm-metricdataquery.md) you write that property `ReturnData` is required, yet just below it is indicated as _Required: No_

![image](https://user-images.githubusercontent.com/18397619/171188294-d4f12110-1ef3-44c3-b34d-4402fcf5cc6d.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
