### ISSUE TITLE
AWS::ECR:PublicRepository is region specific, update documentation to avoid confusion

### ISSUE THREAD

**Issue by cr-trojan23** [awsdocs/aws-cloudformation-user-guide#1235]
`AWS::ECR:PublicRepository` resource is only working in the `us-east-1` region, verified using CloudFormation Template in `us-east-1` and other regions like `ap-south-1`.<br> Cloudformation returns this error when validated in any regions other than `us-east-1`:

>  06/07/2022, 12:49:08 - Template contains errors.: Template format error: Unrecognized resource types: [AWS::ECR::PublicRepository]

However, when the region is set to `us-east-1`, the template is valid.

The [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-publicrepository.html) does provide all the required documentation about the `AWS::ECR:PublicRepository` resource, but it is nowhere mentioned that `AWS::ECR:PublicRepository` works only in the `us-east-1` region.

**Comment by cr-trojan23** [comment]
@rachfop Hi, are you still working on the resource specification as mentioned [here?](https://github.com/awsdocs/aws-cloudformation-user-guide/issues/956#issuecomment-813501383)
This issue still exists after 1.5 years with a missing line of documentation.

**Comment by enteleca** [comment]
Just ran into this issue. I'm wondering if suppert will be added for other regions?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
