### ISSUE TITLE
Document default values for CloudFormation properties

### ISSUE THREAD

**Issue by mnapoli** [awsdocs/aws-cloudformation-user-guide#1239]
This is a follow-up of #272 which was closed without being fixed.

The CloudFormation documentation documents whether a property is required, but it doesn't document the default value when the property is not set.

It would be much more useful to know what the default value is for each optional property.

**Comment by dlenski** [comment]
Thank you. As @rob3c wrote in https://github.com/awsdocs/aws-cloudformation-user-guide/issues/272#issuecomment-1039365850:

> I shudder to think at the collective hours spent by all developers world-wide using CloudFormation and independently wasting their time searching for the same basic information that should obviously be provided by AWS here (or, **if there's a single source of truth for these values for each resource to avoid sync problems, then the CloudFormation docs should maintain links to that info**).

There's clearly a single source-of-truth for default values of CloudFormation properties in the code that implements each CFN entity, but somehow…

* The **HTML** documentation consistently ends up with up-to-date information on these default values
* The *Markdown* documentation in this repository consistently has these default values _wiped out_ when it's regenerated… after end-users take the effort to manually add the default values from the HTML docs (which is [what happened after I contributed some of these in #767](https://github.com/awsdocs/aws-cloudformation-user-guide/pull/767#issuecomment-740074303)).

What we're ultimately asking for here is for the maintainers to ensure that the docs in this repository, which are apparently auto-generated from some underlying source, include **all of the default values for all optional CFN properties everywhere** whenever they're regenerated.

**Comment by mnapoli** [comment]
> The HTML documentation consistently ends up with up-to-date information on these default values

Could you clarify? I've opened this issue because the online docs **do not** systematically contain documentation for default values.

Random example:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/720328/178699704-1268102f-71e6-4a16-bd19-6481c4cf44af.png">

**Comment by dlenski** [comment]
> Could you clarify? I've opened this issue because the online docs do not systematically contain documentation for default values.

You're right, @mnapoli, my statement was wrong.

In https://github.com/awsdocs/aws-cloudformation-user-guide/pull/767#issuecomment-740074303, I explained how I went around hunting for the default values of these parameters, but I found them in human-written _blog posts_ about new features, rather than in the (also auto-generated?) HTML docs.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
