### ISSUE TITLE
Non-breaking spaces in stack-policy example JSON.

### ISSUE THREAD

**Issue by matthewhembree** [awsdocs/aws-cloudformation-user-guide#1240]
File: https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/protect-stack-resources.md

Has NBSP in the example JSON which if copy pasted exactly will not work.

This might affect other snippets, I'm just doing one file. Project admins should consider auditing the snippets.

.
Thanks!

**Comment by HLeeHart** [comment]
Thanks for the report and the fix!
