### ISSUE TITLE
The "Roles and Features" Template Not Functioning

### ISSUE THREAD

**Issue by brentarias** [awsdocs/aws-cloudformation-user-guide#125]
The Windows Server "Roles and Features" template has the following problems:

 - All the ami id's in the "mappings" section are out of date.
 - The EC2 instance types require a VPC, but the template has no parameter or scaffolding to integrate with a VPC.

In short, the template is currently useless.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
