### ISSUE TITLE
AWS::KinesisFirehose::DeliveryStream DynamicPartitioningConfiguration lacks context on how processors should be implemented

### ISSUE THREAD

**Issue by jacobeturpin** [awsdocs/aws-cloudformation-user-guide#1259]
The current documentation around `DynamicPartitioningConfiguration` that can be applied to `ExtendedS3DestinationConfiguration` for a Kinesis Firehose Delivery Stream is very confusing. The DynamicPartitioningConfiguration only contains the Enabled and RetryOptions properties, leaving the user confused on how to actually implement any dynamic partitioning keys.

I was only able to stumble upon how this actually gets applied via a [StackOverflow post](https://stackoverflow.com/a/69047987/3658702) because the documentation lacks clarity than an enabled DynamicPartitioningConfiguration also requires the implementation of a ProcessingConfiguration with Processors of the correct type.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
