### ISSUE TITLE
CodeArtifact repository creation fails when multiple external connections are provided

### ISSUE THREAD

**Issue by yogiwiz** [awsdocs/aws-cloudformation-user-guide#1263]
Steps for repro:
Create/Update a CodeArtifact(AWS::CodeArtifact::Repository) repository with multiple external connections. Stack fails as 'AssociateExternalConnection' API supports only one external connection per repository. https://docs.aws.amazon.com/codeartifact/latest/APIReference/API_AssociateExternalConnection.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
