### ISSUE TITLE
New feature request: extend supported functions in FindInMap

### ISSUE THREAD

**Issue by matke2002** [awsdocs/aws-cloudformation-user-guide#1269]
Hi,
please add more supported functions for `FindInMap`.
Eg. `Sub` and `ImportValue` 
My example:
```yml
CidrBlock: !FindInMap 
        - !Ref AvailabilityZoneId
        - !ImportValue 
          'Fn::Sub': '${ParentVpcStack}-Environmnet'
        - PublicSubnet
```
Thank you

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
