### ISSUE TITLE
Document a custom resource solution for AutoMinorVersionUpgrade property under AWS::RDS::DBInstance resource

### ISSUE THREAD

**Issue by vmusaa** [awsdocs/aws-cloudformation-user-guide#1273]
### Name of the resource

AWS::RDS::DBInstance

### Resource name

AWS::RDS::DBInstance

### Reference Link

1) https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html
2) https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html 

### Details

The AWS::RDS::DBInstance resource results in drift when the `AutoMinorVersionUpgrade`property is set to true and there is a minor version update. This causes the stack to go into drift. 

### Documentation Request - 
1) An update to the documentation for `AutoMinorVersionUpgrade` ([doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html )) parameter that it may result in drift due to out of band changes and the user needs to keep the template updated with current version of the DB instance. 

2) Document a solution with a sample custom resource implementation which queries the current version on the instance and passes it to the `AWS::RDS::DBInstance` resource. In real world, it is usually not a single ops engineer who manages cloud formation templates, and it is difficult for customers to be already be aware of such an issue to occur in future and co-ordinate when it is not documented. Hence, it would be great to have this custom solution or a similar workaround documented either as an AWS Doc or an AWS Blog. 

### Documents/pages where this custom resource solution can be added - 
1) https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.Maintenance.html
2) https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html

#https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1308

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
