### ISSUE TITLE
Image link is broken

### ISSUE THREAD

**Issue by AsadJivani** [awsdocs/aws-cloudformation-user-guide#1283]
The image link on the page [https://docs.aws.amazon.com/AWSCloudFormation/latest/images/console-create-stack-stacks-create-stack.png](https://docs.aws.amazon.com/AWSCloudFormation/latest/images/console-create-stack-stacks-create-stack.png) is broken.
![image](https://user-images.githubusercontent.com/30193048/200197234-363e3b9e-4b9d-43db-8cc6-2a4c5d5d6c68.png)
It looks like the URL is just missing `/UserGuide` before this part `/images`. So the correct URL should be https://docs.aws.amazon.com/images/AWSCloudFormation/latest/UserGuide/images/console-create-stack-stacks-create-stack.png

**Comment by HLeeHart** [comment]
This has been fixed.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-create-stack.html
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/cfn-console-create-stack.md
