### ISSUE TITLE
blue green docs are very confusing.

### ISSUE THREAD

**Issue by dbenader** [awsdocs/aws-cloudformation-user-guide#1285]
I have spent hours trying to setup a simple blue/green deployment via cloudformation following this guide: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html

Unfortunately, this guide does not go into enough detail and is very confusing. Specifically, The example templates have references to 'GreenTaskSet' and 'GreenTaskDefinition', which do not actually exist.

**Comment by dbenader** [comment]
@rachfop

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
