### ISSUE TITLE
The `doc_source` folder has been deleted with no explanations

### ISSUE THREAD

**Issue by aureq** [awsdocs/aws-cloudformation-user-guide#1299]
Hi AWS, Hi @agwug 

In this commit 29564584f8e22af5d9afd621bb05c3da542cfba9, the entire `doc_source` is deleted leaving this repository empty. The commit message only says "Periodic updates 2023-01-05" which doesn't explain why the docs are gone?

If you intention is to effectively delete all docs, could it be possible to:

- State the reason why AWS is deleting them?
- Is there a new location where we should be able to find them?
- If the intention is to delete all the docs, could you revert the commit and archive this repository instead?

Thank you.

**Comment by HLeeHart** [comment]
This mistake was corrected. Thanks for raising the issue.
