### ISSUE TITLE
AWS Transfer Server IdentityProviderDetails confused description.

### ISSUE THREAD

**Issue by w0rmr1d3r** [awsdocs/aws-cloudformation-user-guide#1300]
Hello,

In the description for the property [IdentityProviderDetails](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-server.html#cfn-transfer-server-identityproviderdetails), detailed [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-transfer-server-identityproviderdetails.html).
It says it's only required when the [IdentityProviderType](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-transfer-server.html#cfn-transfer-server-identityprovidertype) is set to either `AWS_DIRECTORY_SERVICE` or `API_GATEWAY`.
According to the property `IdentityProviderType`, when it's set to `AWS_LAMBDA`, `IdentityProviderDetails` are also required.

So, shall I open a PR with that change or have I missed anything?

Thank you in advance

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
