### ISSUE TITLE
 Invalid Yaml: could not determine a constructor for the tag !Sub in 'reader', line 8, column 27: - !Sub 'elasticbeanstalk-${AWS::Re ... ^ , JSON exception: Invalid JSON: Unexpected character (R) at position 0.. Update the configuration file.

### ISSUE THREAD

**Issue by jpswade** [awsdocs/aws-cloudformation-user-guide#1303]
From the documents:
`!Sub 'arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/${vpc}'`

What I'm using:
`!Sub 'elasticbeanstalk-${AWS::Region}-${AWS::AccountId}'`

The error:

```
Invalid Yaml: could not determine a constructor for the tag !Sub in 'reader', line 8, column 27: - !Sub 'elasticbeanstalk-${AWS::Re ... ^ , JSON exception: Invalid JSON: Unexpected character (R) at position 0.. Update the configuration file.
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
