### ISSUE TITLE
AWS Secrets Manager Redshift Serverless Integration

### ISSUE THREAD

**Issue by jbingham17** [awsdocs/aws-cloudformation-user-guide#1305]
As of right now there does not appear to be any integration to allow Secrets Manager to connect to a Redshift Serverless Namespace.

The following code should be supported:
```SecretRedshiftAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId:
        Ref: RedshiftLoginSecret
      TargetId:
        Ref: FWRedshiftServerlessNamespace
      TargetType: AWS::RedshiftServerless::Namespace
```
This fails since `AWS::RedshiftServerless::Namespace` is not a supported `TargetType`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
