### ISSUE TITLE
Need Support: Dynamic refer for Fn::Transform

### ISSUE THREAD

**Issue by pek77** [awsdocs/aws-cloudformation-user-guide#1330]
Hi Team,
Is any possible support Fn::Transform name for dynamic refer?

I wanna use Macro(Fn::Transform) by using dynamic refer, such as `Aws.StackName` or Import Value.

When deploy, it says: Key Name of transform definition must be a string.

Because I deploy a new Macro for name `AWS::StackName`  and wanna use this name for dynamic refer.

```
 "Fn::Transform": {
         "Name": {
          "Ref": "AWS::StackName"
         },
         "Parameters": {
          "InputString": {
           "Ref": "AWS::StackName"
          },
          "Operation": "Lower"
         }
        }
       },
```
Is any possible support this feature?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
