### ISSUE TITLE
Lambda FunctionName Property - Specify Maximum Explicitly

### ISSUE THREAD

**Issue by irby** [awsdocs/aws-cloudformation-user-guide#1333]
In the [LambdaFunction documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html) under the FunctionName property, the description mentions the maximum length of the name is 64 characters, but below its description is specifies a minimum length of 1 but doesn't explicitly have a maximum property. I notice for some other properties it has a maximum explicitly specified. 

I was wondering, for consistency, we could add a `Maximum: 64` to the property's specifications? 

<img width="766" alt="image" src="https://github.com/awsdocs/aws-cloudformation-user-guide/assets/10983811/7b5da0ac-2dae-4359-9b31-e3142b6a5d52">

<img width="299" alt="image" src="https://github.com/awsdocs/aws-cloudformation-user-guide/assets/10983811/4b69f80c-ee8d-4868-b1a4-ee3347fd746b">

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
