### ISSUE TITLE
AWS::EC2::FlowLog does not support S3 delivery

### ISSUE THREAD

**Issue by jasonabradley** [awsdocs/aws-cloudformation-user-guide#137]
The CloudFormation module for FlowLog has not been updated to support S3 delivery target.

**Comment by grusy** [comment]
This was added recently: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-flowlog.html

**Comment by ckesser** [comment]
Thank you @jasonabradley for bringing attention to this! @grusy Yep, looks like the AWS::EC2::FlowLog resource type was updated on 9/20: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html. I'm going to close out this issue. Thanks again to you both!
