### ISSUE TITLE
AWS::SQS::Queue YAML Syntax indentation

### ISSUE THREAD

**Issue by PatMyron** [awsdocs/aws-cloudformation-user-guide#152]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-resource-sqs-queues-syntax

` Tags:`
is improperly indented in the YAML syntax at the top of the page, but it is not part of the source on Github.

**Comment by ckesser** [comment]
Thanks @PatMyron, 'Tags' indentation is fixed: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html#aws-resource-sqs-queues-syntax
