### ISSUE TITLE
Verification type of email verification messages in "Cognito/User Pools" not documented

### ISSUE THREAD

**Issue by MattPark** [awsdocs/aws-cloudformation-user-guide#159]
When attempting to automate the configuration of Cognito User Pools with Cloudformation, the "verification type" radio button within does not seem to be a documented configuration.  How do you flip this radio button?

![image](https://user-images.githubusercontent.com/1690680/45604252-8a6d8600-ba00-11e8-9d64-9007193d37f6.png)

**Comment by stonempv** [comment]
+1

**Comment by JoeAlamo** [comment]
I would also like to know this.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
