### ISSUE TITLE
valid values for codedeploy compute platform 

### ISSUE THREAD

**Issue by palsarma** [awsdocs/aws-cloudformation-user-guide#17]
doc_source/aws-resource-codedeploy-application.md: 

Type: "AWS::CodeDeploy::Application"
Properties:
  ApplicationName: String	    
  ComputePlatform: String

ComputePlatform should specify the valid values.

**Comment by palsarma** [comment]
Submitted a PR https://github.com/awsdocs/aws-cloudformation-user-guide/pull/18

**Comment by AWSRandall** [comment]
Thanks, this is awesome! I appreciate the helpful feedback!

Thanks for using CloudFormation!

I'll merge the PR shortly.
