### ISSUE TITLE
Amazon Cognito UserPool LambdaConfig missing UserMigration

### ISSUE THREAD

**Issue by christemple** [awsdocs/aws-cloudformation-user-guide#178]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html

I've just tried configuring a UserPool with a `UserMigration` lambda similar to how we do `PreSignUp` and `CustomMessage` and it fails template validation for `LambdaConfig`.

Given that you can configure `UserMigration` in the exact same way as the other lambda config options using the aws cli I was hoping it was just undocumented in the CloudFormation docs.

I'd really appreciate this functionality being added to `LambdaConfig`, it would avoid us having to write post stack creation scripts using the aws cli to update the UserPool afterwards.

By having a dependency on the `UserMigration` trigger it has rendered the `LambdaConfig` config unusable because if we have to update the pool post creation, we might as well keep all trigger updates together.

If it's as simple as adding validation for the config and if that code is open source, let me know and I'll happily add it.

**Comment by stephenhuh** [comment]
On top of this, it does seem that the UserPool LambdaConfig does not mention what type of string it is accepting, or specify if it is an ARN

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/59

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-usermigration
