### ISSUE TITLE
Ambigous statements in DBClusterParameterGroupName

### ISSUE THREAD

**Issue by anshrma** [awsdocs/aws-cloudformation-user-guide#179]
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-rds-dbcluster.md

DBClusterParameterGroupName The name of the DB cluster parameter group to associate with this DB cluster.
If this argument is omitted, default.aurora5.6 is used. If default.aurora5.6 is used, specifying aurora-mysql or aurora-postgresql for the Engine property **might** result in an error. Required: No

Will it result in an error or not ??? Specifying "might" result in an error is pretty ambigous.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
