### ISSUE TITLE
aws-resource-events-eventbuspolicy does not exists in Repo

### ISSUE THREAD

**Issue by melih154** [awsdocs/aws-cloudformation-user-guide#201]
While trying to create PR for redundant "," character on `Type: AWS::Events::EventBusPolicy,` on the last YAML sample, clicked Edit on Github page and got 404 for https://github.com/awsdocs/aws-cloudformation-user-guide/tree/master/doc_source/aws-resource-events-eventbuspolicy.xml

Guessing all AWS Documentation pages are on this repo and this one is missing.

**Comment by PatMyron** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbuspolicy.html

**Comment by melih154** [comment]
Just to recap:

**Comment by PatMyron** [comment]
@melih154 I think the Github repository is just behind the internal repository used to generate the site

**Comment by ckesser** [comment]
I'm very late to this discussion, but yes @PatMyron is correct; the GitHub repo was not up-to-date. It is now, so I'll close this out.
