### ISSUE TITLE
Add a NOTE in EC2 LaunchTemplate NetworkInterfaces for Security groups

### ISSUE THREAD

**Issue by naren-black** [awsdocs/aws-cloudformation-user-guide#204]
Please put a NOTE in the following resource property that when creating networking interfaces, security groups needs to specified using the Groups property:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-securitygroupids

**Comment by julieso** [comment]
Thanks for the suggestion. I've added "If you specify a network interface, you must specify any security groups and subnets as part of the network interface." to the description of NetworkInterfaces: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-networkinterfaces
