### ISSUE TITLE
Change EC2 LaunchTemplate InstanceMarketOptions to "Required"

### ISSUE THREAD

**Issue by naren-black** [awsdocs/aws-cloudformation-user-guide#205]
When "InstanceMarketOptions" is used in "AWS::EC2::LaunchTemplate", the "MarketType" property is required. If not given the stack throws error:
You must use a valid fully-formed launch template. The request must contain the parameter MarketType

**Comment by julieso** [comment]
Thanks for the feedback. I have marked it as conditional in the HTML documentation, which will get the markdown updated: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-instancemarketoptions.html#cfn-ec2-launchtemplate-launchtemplatedata-instancemarketoptions-markettype.

**Comment by tmadms** [comment]
Is it possible to add an allowed value for 'on-demand'?

I'm trying to integrate this in to my cloud formation stack using the launch template resource and I'd like to specify in a parameter the market options type, for example:

InstanceMarketTypeParameter:
    Type: String
    Default: on-demand
    AllowedValues:
      - on-demand
      - spot

Or is there a better workaround to this?
