### ISSUE TITLE
Elastic Load Balancing ListenerRule Actions for Redirect Policy

### ISSUE THREAD

**Issue by stewmi** [awsdocs/aws-cloudformation-user-guide#208]
The documentation currently states:

TargetGroupArn The Amazon Resource Name (ARN) of the target group to which Elastic Load Balancing routes the traffic.
Required: Yes
Type: String

It appears that this is a conditional requirement as an error is thrown if this property is defined with type 'redirect'

**Comment by julieso** [comment]
Apologies for the delayed response. Current documentation does not show as required, and describes it as supported only when 'Type' is 'forward'.
