### ISSUE TITLE
Fix description in aws-resource-dms-replicationtask.md

### ISSUE THREAD

**Issue by danielkr85** [awsdocs/aws-cloudformation-user-guide#235]
The description for **ReplicationTaskIdentifier** appears to be incorrect. It says _"The ARN string that uniquely identifies the endpoint."_, which is the same as the description for **TargetEndpointArn**.

**Comment by ckesser** [comment]
Hi @danielkr85, I'm sorry for such a late response to this Issue. This is accurate, and it's since been resolved. Closing this out. Thanks so much for the feedback!
