### ISSUE TITLE
SageMaker::Endpoint and SageMaker::EndPointConfig Tags should not be required

### ISSUE THREAD

**Issue by markpeek** [awsdocs/aws-cloudformation-user-guide#239]
Per the cloudformation specification files the Tags properties are not required. However, [Endpoint](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-sagemaker-endpoint.md#aws-resource-sagemaker-endpoint-properties) and [EndpointConfig](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-sagemaker-endpointconfig.md) documentation lists Tags as required.

**Comment by ckesser** [comment]
Another one that's since been fixed. Thanks, @markpeek! Closing.
