### ISSUE TITLE
Suggestion: Move examples up on cloudformation resource documentation

### ISSUE THREAD

**Issue by paulopontesm** [awsdocs/aws-cloudformation-user-guide#252]
One of the things that is really nice about terraform is seeing the *Examples* section as 
soon as I open the page:

https://www.terraform.io/docs/providers/aws/r/instance.html

I think that moving the examples to the begging would make it more welcoming for newcomers.

**Comment by h314to** [comment]
I agree. In addition, having syntax highlight on the examples would make also make them more legible.

**Comment by rachfop** [comment]
Thank you for your request. I'll add it to the team's list of items for future consideration and then close this issue.
