### ISSUE TITLE
DeploymentController not supported

### ISSUE THREAD

**Issue by naataaniitsosie** [awsdocs/aws-cloudformation-user-guide#254]
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-deploymentconfiguration

Can we add support for "DeploymentController"? See the links above for more clarification. The ECS api supports this attribute when creating a service. However, Cloudformation does not.

**Comment by rahworkx** [comment]
I as well would like to show support for a definition to be added in cloudformation.

**Comment by gkessman** [comment]
Bump, I'd also like support added for DeploymentController in CloudFormation. Hopefully this can be resolved soon

**Comment by gkessman** [comment]
Is there any plan to add this property to ECS Service creation through Cloudformation?

**Comment by PatMyron** [comment]
[`AWS::ECS::Service.DeploymentController`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-deploymentcontroller) is now supported in CloudFormation

[Release History](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)
