### ISSUE TITLE
Missing properties for ElasticSearch Domain

### ISSUE THREAD

**Issue by nason** [awsdocs/aws-cloudformation-user-guide#257]
I'm unable to provision a AWS ES Domain via CloudFormation because I need the node-to-node encryption feature enabled, and that can only be done at creation time.

There are few properties supported via API, but not in CloudFormation for a `AWS::Elasticsearch::Domain`: 
- `NodeToNodeEncryptionOptions`
- `LogPublishingOptions`
- `CognitoOptions`

If I try to include

```yaml
NodeToNodeEncryptionOptions:
  Enabled: true
```

I get a CREATE_FAILED with the reason `Encountered unsupported property NodeToNodeEncryptionOptions`

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-configuration-api.html#es-configuration-api-actions-createelasticsearchdomain

**Comment by cmmeyer** [comment]
Hi @nason -- this feature is not yet supported by CloudFormation. The CloudFormation coverage team has it on their backlog and it should be coming in an upcoming release. You can track coverage releases here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html

**Comment by mscharp** [comment]
> it should be coming in an upcoming release

This could mean next week or a year from now.  Any insight into how soon this might be accomplished?  Without this, I'm unable to use cloud formation to create my ElasticSearch cluster.  I could create a script to use the API, but that would be different than how we deploy everything else...

**Comment by rhbecker** [comment]
from the release history @cmmeyer linked, this appears to have been released on February 21, 2019 ... should this issue be closed?

**Comment by yetanotherbug** [comment]
@rhbecker LogPublishingOptions is still missing as far as I can tell.

**Comment by rhbecker** [comment]
Yeah, you're right ... and maybe `CognitoOptions` remains unsupported as well. Apparently I was fixated on `NodeToNodeEncryptionOptions` when I left my previous comment.

**Comment by s177437** [comment]
We are also missing this the `LogPublishingOptions` functionality for CloudFormation. Hope this is an added feature in the future :)

**Comment by mscharp** [comment]
It also looks like DomainEndpointOptions are not supported yet either.

From the CLI: --domain-endpoint-options

{
  "EnforceHTTPS": true|false,
  "TLSSecurityPolicy": "Policy-Min-TLS-1-0-2019-07"|"Policy-Min-TLS-1-2-2019-07"
}

**Comment by PatMyron** [comment]
[`AWS::Elasticsearch::Domain`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticsearch-domain.html) now supports `NodeToNodeEncryptionOptions`, `LogPublishingOptions`, and `CognitoOptions`

https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/54
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/55

[Release History](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html)

---

@mscharp `DomainEndpointOptions` support is being tracked here:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/201

**Comment by vshah-lifesize** [comment]
@PatMyron When's this expected to go out?
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/201
