### ISSUE TITLE
SqsParameters is missing in Rule Target docs

### ISSUE THREAD

**Issue by markpeek** [awsdocs/aws-cloudformation-user-guide#264]
SqsParameters is missing from the [Rule Target](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-target.html) docs. It does appear in the resource specification files.

**Comment by ckesser** [comment]
Again, sorry for the months of silence. This has been fixed, so I'll close this one as well.
