### ISSUE TITLE
Cannot add custom security groups when using MixedInstancesPolicy

### ISSUE THREAD

**Issue by arunasank** [awsdocs/aws-cloudformation-user-guide#270]
Thank you for introducing the `MixedInstancesPolicy` property in `AWS::AutoScaling::AutoScalingGroup`! It's going to make the use of spot instances much easier.

## Cannot specify custom security groups, when using this policy

From the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html), it looks like specifying this property means that you lose the opportunity to specify the security group associated with the `AutoScalingGroup`, since the security group property is added to `AWS::AutoScaling::AutoScalingGroup` through the `LaunchConfiguration` property, and one can only specify one of `LaunchConfiguration`, `MixedInstancesPolicy` or `LaunchTemplate`. 

Please clarify how to specify a custom security group, when using this property.

**Comment by Reneehi** [comment]
I realize this question is a few months old now, but just to follow up. You cannot specify a launch configuration. MixedInstancesPolicy requires a launch template. Therefore, the security group property is specified as part of the launch template. For more information, take a look at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-autoscaling-autoscalinggroup-mixedinstancespolicy.html

There is more information in the user guide for Amazon EC2 Auto Scaling about mixed instances groups and launch templates. Links below:
https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html
https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html

Thanks for your question!

**Comment by arunasank** [comment]
@Reneehi I was so silly to have missed that. 😅 Thank you for your help!
