### ISSUE TITLE
AWS::ServiceDiscovery - release notes have incorrect update descriptions

### ISSUE THREAD

**Issue by markpeek** [awsdocs/aws-cloudformation-user-guide#271]
Feb 7, 2019 update shows the below descriptions but they need to be reversed as InstanceAttributes is a property of AWS::ServiceDiscovery::Instance and DNSConfig is a property of AWS::ServiceDiscovery::Service.
```
The following resources were updated: AWS::ServiceDiscovery::Instance and AWS::ServiceDiscovery::Service.

AWS::ServiceDiscovery::Instance
The DNSConfig property is no longer required.

An update to the HealthCheckCustomConfig property now requires replacement.

AWS::ServiceDiscovery::Service
The InstanceAttributes property now takes a String map value.
```

**Comment by ckesser** [comment]
Sorry for the very late response here, @markpeek. This has been fixed, so I'll close out this Issue. Thank you for pointing this out!
