### ISSUE TITLE
alphanumeric in mapping

### ISSUE THREAD

**Issue by zlxie1992** [awsdocs/aws-cloudformation-user-guide#282]
In the doc
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/mappings-section-structure.md

it says "The name can contain only alphanumeric characters (A-Za-z0-9)."

But in examples, there's "us-east-1" as attribute name

And I tried myself, cloudFormation would not allow "-" in mapping except 1st 2nd level

Would love to have clarification of this.

**Comment by ckesser** [comment]
Thanks for the feedback! Looking at the doc, it states that the name can only contain alphanumeric characters. The name in the examples is HVM64, while us-east-1 is the key. From my reading of this topic, the docs are accurate. Feel free to let me know if I'm off-base here and I can take another look.

**Comment by zlxie1992** [comment]
Umm, please at least clarify which level allows "-" then.

This will work
 "Mappings":{
    "VPC": {
      "us-east-1": {
        "Prod": "vpc-12345678"
      }
   }
}

But this will not:

 "Mappings":{
    "VPC": {
      "US": {
        "us-east-1": {
          "Prod": "vpc-12345678"
        }
      }
   }
}
