### ISSUE TITLE
UserPool LambdaConfig does not mention what type of string it is accepting or specify if it is an ARN

### ISSUE THREAD

**Issue by stephenhuh** [awsdocs/aws-cloudformation-user-guide#287]
UserPool LambdaConfig strings don't specify what the string is supposed to be.
Broken off from #178 and opened as a separate issue.
[link](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html)

**Comment by patrickgreenwell** [comment]
Looks like the docs now list the pattern as an arn, added in commit 93aedc700d This can be closed now i'm guessing?

**Comment by rachfop** [comment]
aws-cloudformation/aws-cloudformation-coverage-roadmap#59

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-lambdaconfig.html#cfn-cognito-userpool-lambdaconfig-usermigration
