### ISSUE TITLE
Incorrect examples in doc_source/aws-resource-docdb-dbclusterparametergroup.md

### ISSUE THREAD

**Issue by nabuskey** [awsdocs/aws-cloudformation-user-guide#289]
DocumentDB parameter group examples in `doc_source/aws-resource-docdb-dbclusterparametergroup.md` shows incorrect data structure for the "Parameters" property. It should be mappings but an array is shown.

This is the format referenced by documentation which fails in CF with error message, "Property validation failure: [Value of property {/Parameters} does not match type {Map}]". 
```
  DocDBClusterParamterGroup:
    Type: "AWS::DocDB::DBClusterParameterGroup"
    Properties:
      Description: Test Parameter group
      Family: docdb3.6
      Name: test1
      Parameters :
        -
          Name: "tls"
          Value: "enabled"
```
This works.
```
  DocDBClusterParamterGroup:
    Type: "AWS::DocDB::DBClusterParameterGroup"
    Properties:
      Description: Test Parameter group
      Family: docdb3.6
      Name: test1
      Parameters :
        tls: enabled
```

**Comment by TruffleMuffin** [comment]
Found this from google search for this exact problem, original issue is correct and is still not fixed.

**Comment by polarizeme** [comment]
Over 2 years later, the documentation on this is still incorrect for both YAML and JSON; using the provided JSON format of:
```
"Properties" : {
  "Description" : "description",
  "Family" : "docdb3.6",
  "Name" : "sampleParameterGroup",
  "Parameters" :  [
    "audit_logs": "disabled",
    "tls": "enabled",
    "ttl_monitor": "enabled"
  ],
  "Tags" : [{ "Key": "String","Value": "String" }]
}
```

For the "Parameters" property results in the same "Property validation failure: [Value of property {/Parameters} does not match type {Map}]" error as reported by @nabuskey for YAML.

Again, as with YAML, the fix is comically easy:
```
"Properties" : {
  "Description" : "description",
  "Family" : "docdb3.6",
  "Name" : "sampleParameterGroup",
  "Parameters" :  {
    "audit_logs": "disabled",
    "tls": "enabled",
    "ttl_monitor": "enabled"
  },
  "Tags" : [{ "Key": "String","Value": "String" }]
}
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
