### ISSUE TITLE
AvailabilityZones property description for "AWS::DAX::Cluster" resource causing confusion for customers 

### ISSUE THREAD

**Issue by razhamma** [awsdocs/aws-cloudformation-user-guide#295]
The description for AvailabilityZones property for "AWS::DAX::Cluster" resource should be like:

AvailabilityZones
    All nodes belonging to the cluster are placed in these Availability Zones. Use this parameter if you want to distribute the nodes across multiple AZs. Following are different cases when dealing with AWS::DAX::Cluster through CloudFormation and specifying this property:
   a- Cluster Creation
        You must specify one AZ per DAX node in the cluster.
   b- Cluster Update - Adding new DAX Nodes in the Cluster
        When specifying preferred availability zones for new DAX nodes, the number of nodes to create must match the number of preferred availability zones. You must specify one AZ per new expected DAX node in the cluster. For example, if you are adding two nodes, the AvailabilityZones property should have two AZs so that DAX service will create these new nodes into specified AZs.
   c- Cluster Update - Deleting Nodes from the DAX Cluster
        When specifying preferred availability zones for DAX nodes to be deleted from, list of availability zones must equal the difference between the current list of nodes in the cluster and the new replication factor. You must specify one AZ per deletion expected DAX node in the cluster. For example, if you are deleting two nodes from DAX cluster with current size of 10 nodes, the AvailabilityZones property should have two AZs so that DAX service will delete these two nodes from specified AZs.

**Comment by razhamma** [comment]
After further testing and bug fix application:
The new proposed wording should be as follow:

### AWS::DAX::Cluster:
**AvailabilityZones:**
Should be the expected end state of cluster nodes after create or update action has been applied on the cluster. The Availability Zones (AZs) in which all the cluster nodes(pre-existing and new ones) will reside after the cluster has been created or updated. The length of this list must equal the ReplicationFactor property's value. Use this parameter if you want to distribute the nodes across multiple AZs.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
