### ISSUE TITLE
ReplicationFactor property description for "AWS::DAX::Cluster" resource causing confusion for customers

### ISSUE THREAD

**Issue by razhamma** [awsdocs/aws-cloudformation-user-guide#296]
The description for ReplicationFactor property for "AWS::DAX::Cluster" resource should be like:

ReplicationFactor
    The number of nodes in the DAX cluster. 
    Following are different cases when dealing with AWS::DAX::Cluster through CloudFormation and specifying this property:

   a- Cluster Creation
        A replication factor of 1 will create a single-node cluster, without any read replicas. For additional fault tolerance, you can create a multiple node cluster with one or more read replicas. To do this, set ReplicationFactor to 2 or more.
        Note
           AWS recommends that you have at least two read replicas per cluster.

   b- Cluster Update - Adding new DAX Nodes in the Cluster
        Specify this property as the sum of currently available DAX nodes in the cluster and the number of new Nodes you want to add. For example, if there are '3' DAX Nodes currently then to add '2' more nodes, the ReplicationFactor property should be specified as '5'.
       Note 
           DAXCluster cannot be scaled up further if there are already '10' DAX Nodes available in the cluster. 

   c- Cluster Update - Deleting Nodes from the DAX Cluster
       Specify this property as the difference of currently available DAX nodes in the cluster and the number of DAX nodes you want to delete. For example, if there are '10' DAX Nodes currently then to delete '2' nodes, the ReplicationFactor property should be specified as '8'.
       Note
           DAXCluster cannot be scaled down further if there is only '1' DAX Node available.

**Comment by razhamma** [comment]
After further testing and bug fix application:
The new proposed wording should be as follow:

### AWS::DAX::Cluster:
**ReplicationFactor:**
The number of nodes in the DAX cluster. A replication factor of 1 will create a single-node cluster, without any read replicas. For additional fault tolerance, you can create a multiple node cluster with one or more read replicas. To do this, set ReplicationFactor to 2 or more. This must be equal to the number of AZs in AvailabilityZones property.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
