### ISSUE TITLE
Get Attributes for Subnet is missing CidrBlock

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#298]
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-ec2-subnet.md#fngetatt

One thing we noticed is that GetAtt does not work for CidrBlock (IPv4) for Subnets.  IPv6 CIDRs work, but the CidrBlock is missing.

Should this be a feature request as well?

**Comment by julieso** [comment]
Apologies for the delayed response. The resource spec doesn't include CidrBlock as an attribute. I will pass on your request. With Ipv6CidrBlocks, I'd expect to get an IPv6 CIDR block if one is associated with my subnet.
