### ISSUE TITLE
EC2 VPC Endpoint Required Conditional Parameters

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#299]
For 

SubnetIds and SecurityGroupIds, should the Required fields be Conditional?  For example, for a Interface Endpoint if SubnetIds aren't specified, the Cloudformation will not create.

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-ec2-vpcendpoint.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
