### ISSUE TITLE
Incorrect version strings on AmazonMQ

### ISSUE THREAD

**Issue by kisst** [awsdocs/aws-cloudformation-user-guide#310]
As @smckenzie23 closed [this issue](https://github.com/awsdocs/amazon-mq-developer-guide/issues/1) without any change in the docs, looks like that the reference to the MQ docs about the `EngineVersion` properties shouldn't be used in the CFN documentation, at least not without additional information about how to interpret the referred documentation, as that in the current state is misleading.

Might need some internal effort across documentation teams to assure that this kind of errors do not accrue.

**Comment by PatMyron** [comment]
Sorry about this poor experience. The example sections for both [`AWS::AmazonMQ::Broker`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-broker.html#aws-resource-amazonmq-broker--examples) and [`AWS::AmazonMQ::Configuration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-amazonmq-configuration.html#aws-resource-amazonmq-configuration--examples) now have examples using `EngineVersion`

---

The [CloudFormation Linter](https://github.com/aws-cloudformation/cfn-python-lint/) can also help catch these before deploying:

```
E3030 You must specify a valid value for EngineVersion (ActiveMQ 5.15.9).
Valid values are ["5.15.0", "5.15.6", "5.15.8", "5.15.9"]
template.yaml:5:7

E3030 You must specify a valid value for EngineVersion (ActiveMQ 5.15.9).
Valid values are ["5.15.0", "5.15.6", "5.15.8", "5.15.9"]
template.yaml:18:7
```

After installing the Linter, the accompanying [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=kddejong.vscode-cfn-lint) can automatically run it:

<img width="741" alt="Screen Shot 2020-01-26 at 8 43 56 PM" src="https://user-images.githubusercontent.com/7014355/73150732-977e9880-407c-11ea-81ca-f9916656771d.png">
