### ISSUE TITLE
configuring logs for an elasticsearch domain

### ISSUE THREAD

**Issue by rhbecker** [awsdocs/aws-cloudformation-user-guide#313]
Is it on the CloudFormation coverage team's roadmap to support [configuration of logs for an elasticsearch domain](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-createupdatedomains.html#es-createdomain-configure-slow-logs)?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
