### ISSUE TITLE
cannot get to AWS::CloudWatch::Dashboard page

### ISSUE THREAD

**Issue by palsarma** [awsdocs/aws-cloudformation-user-guide#315]
Looks like the link to this page is broken
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-dashboard.html

it is redirecting me to the welcome page

**Comment by ckesser** [comment]
Hi @palsarma, Thank you for pointing this out, I'm working on resolving it. Will check back here soon.

**Comment by robertsigler** [comment]
It looks like the `AWS::CloudWatch::Dashboard` page is fixed, but this same issue is happening to me for this page now:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-customactiontype-configurationproperties.html

**Comment by rachfop** [comment]
Hello @robertsigler and @palsarma thank you for your suggestions. CodePipeline/CW issues is now resolved.
