### ISSUE TITLE
No Resource Specification for ap-east-1

### ISSUE THREAD

**Issue by fatbasstard** [awsdocs/aws-cloudformation-user-guide#320]
There's a new region: ap-east-1 (https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-hong-kong-region/).

But the Resource Specification is not available:

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/d9c372b5277cf3af05b3814d50618699aa086e07/doc_source/cfn-resource-specification.md

**Comment by PatMyron** [comment]
Seems to be missing for the  GovCloud and Chinese regions as well

**Comment by PatMyron** [comment]
Looks like `ap-east-1` and GovCloud specs might be here:

https://github.com/aws-cloudformation/cfn-python-lint/blob/2164a1a717112a4633f0b0a0f77d23c7724ef858/src/cfnlint/maintenance.py#L31

https://github.com/aws-cloudformation/cfn-python-lint/blob/2164a1a717112a4633f0b0a0f77d23c7724ef858/src/cfnlint/maintenance.py#L49-L50

**Comment by ScriptAutomate** [comment]
Looks like they were added. Can be closed now.

**Comment by fatbasstard** [comment]
Looks ok indeed. Closed the issue
