### ISSUE TITLE
Required AppSync properties documented as not required

### ISSUE THREAD

**Issue by adilosa** [awsdocs/aws-cloudformation-user-guide#321]
It seems many properties of AppSync resources are document as "Required: No" when they are in fact Conditionally Required, or straight up Required. 

For `AWS::AppSync::Resolver`:
* `Kind` is conditionally required, if the resolver is a pipeline resolver. it defaults to `'UNIT'`.
* `PipelineConfig` is conditionally required if `Kind` is `'PIPELINE'`
* `DataSourceName` is conditionally required if `Kind` is `'UNIT'`
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-resolver.html#cfn-appsync-resolver-fieldname

For `AWS::AppSync::Resolver PipelineConfig`:
* `Functions` is required, and should be a list of AWS::AppSync::FunctionConfiguration Names (as best I can tell, found [here](https://medium.com/@joshua.a.kahn/building-aws-appsync-pipeline-resolvers-with-aws-cloudformation-d57d648ecd34))

For `AWS::AppSync::FunctionConfiguration`:
* `Name` is required – results in a 'Name cannot be null' error otherwise
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appsync-functionconfiguration.html

**Comment by KristinaPeterson** [comment]
Thank you for your feedback. I am investigating this issue and will provide you with updates here.

**Comment by KristinaPeterson** [comment]
The "Required" field for each property is auto-generated from the resource specification. I've submitted a ticket for these values to be investigated and corrected in the resource spec. The source documentation will be updated after the specification is updated.
