### ISSUE TITLE
Update description for instanceprofile roles property

### ISSUE THREAD

**Issue by atkinsonm** [awsdocs/aws-cloudformation-user-guide#324]
The `Roles` property of `AWS::IAM::InstanceProfile` seems to suggest that a list of roles is accepted:

![image](https://user-images.githubusercontent.com/3342243/57152973-14f1d280-6da3-11e9-8df0-bd77474094e0.png)

However, per [doc_source/aws-resource-iam-instanceprofile.md](doc_source/aws-resource-iam-instanceprofile.md), only one role is accepted:

> Currently, you can assign a maximum of one role to an instance profile.

Assigning multiple roles may be falsely accepted by tools like `validate-template` checking against the spec. This should be resolved to avoid errors during stack operations when a user attempts to assign multiple roles.

**Comment by rachfop** [comment]
Thanks for the feedback. You can see the updates here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-instanceprofile.html
"Only one role can be assigned to an EC2 instance at a time, and all applications on the instance share the same role and permissions."
