### ISSUE TITLE
Incorrect AWS::AutoScalingPlans::ScalingPlan CustomizedLoadMetricSpecification.Statistic Allowed Values

### ISSUE THREAD

**Issue by tomislacker** [awsdocs/aws-cloudformation-user-guide#328]
## Background
[doc_source/aws-properties-autoscalingplans-scalingplan-customizedloadmetricspecification.md](../blob/master/doc_source/aws-properties-autoscalingplans-scalingplan-customizedloadmetricspecification.md) indicates the `Statistic` property can be any one of:
* `Average`
* `Maximum`
* `Minimum`
* `SampleCount`
* `Sum`

## Problem
When running this through CloudFormation, an error is received at least when using `Average`:
> A customized load metric specification must have statistic 'Sum' (Service: AWSAutoScalingPlans; Status Code: 400; Error Code: ValidationException; Request ID: REDACTED)

## A/C
* If the CloudFormation service _should_ support other `Statistic` values, then this is a CloudFormation bug.
    _If someone with AWS would be able to confirm this, I'll happily file a support ticket._
* If the CloudFormation service **only** supports the `Sum` value for this `Statistic` property, the document needs to be changed and ideally also include some additional details about the period & evaluation periods will be assessed with such a statistical calculation

**Comment by Reneehi** [comment]
Hello,  

Thanks for your question. I realize this question is a few weeks old. Sorry for the delay. The docs are correct. The only valid value is Sum. You can see this in the description. "Currently, the value must always be Sum." We currently do not support any other CloudWatch statistic for this property.

To answer the second question, the Sum data must be aggregated to match the 1 hour granularity of the forecast. You might find this page of our docs helpful: https://docs.aws.amazon.com/autoscaling/plans/userguide/gs-create-scaling-plan.html. We're currently looking at improving the AWS Auto Scaling documentation. That should be done within the next few weeks.

Thanks again for your question.

Regards,
Renee
Technical Writer
Amazon Web Services
