### ISSUE TITLE
The 2nd paragraph of KmsKeyId description is wrong

### ISSUE THREAD

**Issue by phoenix-zhu** [awsdocs/aws-cloudformation-user-guide#333]
Here in this doc, https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-rds-database-instance.md, the 2nd paragraph of `KmsKeyId` is

> If you specify the SourceDBInstanceIdentifier property, the value is inherited from the source DB instance if the read replica is created in the same region. If you specify this property when you create a read replica from an unencrypted DB instance, the read replica is encrypted.

Actually, we can't create an encrypted replica from an unencrypted DB instance, or I misunderstood this part?

**Comment by randyurbano** [comment]
Thanks for the feedback. I corrected the issue:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html

Let me know if you have more questions or comments. Also, please let me know if I can close this issue.
