### ISSUE TITLE
AWS Cloudformation Docs for Secrets Manager doesn't match behavior for Secrets Strings

### ISSUE THREAD

**Issue by dmccorm2** [awsdocs/aws-cloudformation-user-guide#344]
Both GenerateSecretString and SecretString Property descriptions state you must have one or both of these properties.  However, when deploying Secrets Manager with neither property, the Cloudformation stack creation is successful, and generates a Secrets Manager with no secret set (our desired state).  I think these property descriptions should be updated to  state both are optional, as a secret can be created via Cloudformation with no secret set.

doc_source/aws-resource-secretsmanager-secret.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
