### ISSUE TITLE
AWS::AmazonMQ::Broker has invalid examples

### ISSUE THREAD

**Issue by jmkgreen** [awsdocs/aws-cloudformation-user-guide#347]
They use SINGLE_INSTANCE deployment mode yet list multiple subnets which results in an error.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
