### ISSUE TITLE
Wrong Reference on AWS::ApiGateway::Deployment AccessLogSetting page

### ISSUE THREAD

**Issue by DamirAinullin** [awsdocs/aws-cloudformation-user-guide#348]
At the end of page
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-apigateway-deployment-accesslogsetting.md:

## See Also<a name="aws-properties-apigateway-deployment-accesslogsetting--seealso"></a>
+ [accessLogSettings](https://docs.aws.amazon.com/api-reference/resource/stage/#accessLogSettings) in the *Amazon API Gateway REST API Reference*

https://docs.aws.amazon.com/api-reference/resource/stage/#accessLogSettings is incorrect reference.

**Comment by dianeo** [comment]
Good catch, thanks! I'll publish the fix later today or tomorrow.
