### ISSUE TITLE
AWS::CloudFront::Distribution LambdaFunctionAssociation - missing IncludeBody property

### ISSUE THREAD

**Issue by TeemuKoivisto** [awsdocs/aws-cloudformation-user-guide#349]
In the file https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-cloudfront-distribution-lambdafunctionassociation.md is explained that LambdaFunctionAssociation can receive only two parameters, however from the console and the documentation for the actual data type you know there's also `IncludeBody` checkbox https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_LambdaFunctionAssociation.html

What makes the problem the more annoying is, that CloudFormation refuses to launch the stack with clearly a parameter that exists
`Property validation failure: [Encountered unsupported properties in {/DistributionConfig/DefaultCacheBehavior/LambdaFunctionAssociations/0}: [IncludeBody]]`

Can this be fixed? I think it's obvious that this is a bug, and it's annoying to manually having to tick the `Include body` option from the console.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
