### ISSUE TITLE
RoleMappings has wrong type in localized documentation

### ISSUE THREAD

**Issue by wolruf** [awsdocs/aws-cloudformation-user-guide#351]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html
shows RoleMappings with type JSON

in other locales, French for e.g, RoleMappings has a very different type: String to RoleMapping object map

Can the localized doc be fixed ?

**Comment by jlee95** [comment]
This doc looks the same in french: https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-identitypoolroleattachment.html

CloudFormation docs labels all map types as JSON. The description under the property specifies that it is a "string to the RoleMapping object map." 

I don't think there's an issue here.

**Comment by wolruf** [comment]
since last year, yes, the documention probably got updated in the mean time
