### ISSUE TITLE
AWS::RDS::DBInstance says you can't create Multi-AZ replicas

### ISSUE THREAD

**Issue by hltbra** [awsdocs/aws-cloudformation-user-guide#361]
The [SourceDBInstanceIdentifier](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#cfn-rds-dbinstance-sourcedbinstanceidentifier) property has an *Important* note that says:

> If you specify SourceDBInstanceIdentifier, don't set the MultiAZ property to true, and don't specify the DBSnapshotIdentifier property. You can't deploy read replicas in multiple Availability Zones, and you can't create a read replica from a snapshot.

(Source: https://github.com/awsdocs/aws-cloudformation-user-guide/blame/master/doc_source/aws-properties-rds-database-instance.md#L384)

However, [last year RDS released multi-AZ support to PostgreSQL replicas](https://aws.amazon.com/about-aws/whats-new/2018/06/rds-postgres-supports-readreplicas-multiaz/):

> Amazon RDS Read Replicas for PostgreSQL can now be deployed in a Multi-AZ configuration.

 Is this an error in the documentation or doesn't CloudFormation support that yet?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
