### ISSUE TITLE
AWS::CloudFormation::Authentication not working on eu-central-1

### ISSUE THREAD

**Issue by w32-blaster** [awsdocs/aws-cloudformation-user-guide#37]
AWS::CloudFormation::Authentication mechanism can not be used when authenticating to S3 in a bucket located in eu-central-1 (Frankfurt) region. This is because that region only supports authentication with AWS4-HMAC-SHA256.

Please clarify this in the documentation or give examples how to use it when working in that region.

**Comment by rachfop** [comment]
The resource specification reports what is allowed in each region: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html
