### ISSUE TITLE
Inaccuracy of Engine property in RDS instance resource

### ISSUE THREAD

**Issue by abuja** [awsdocs/aws-cloudformation-user-guide#374]
The `Engine` property in `AWS::RDS::DBInstance` is is incorrectly linked to RDS Cluster API. There was a similar issue #327 reported and then closed in May but the same issue still exists as of 6/10/2019 in both source and the latest build from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-database-instance.html#aws-properties-rds-database-instance-syntax

Please see MD source line below and it is fixed in a new PR #373 

> https://github.com/awsdocs/aws-cloudformation-user-guide/blame/06f1a219aa82f2dfc76cf7eec1ce93384ee6b977/doc_source/aws-properties-rds-database-instance.md#L355

**Comment by ckesser** [comment]
Thanks for resurfacing this feedback, @abuja. I'm going to close out this Issue in favor of the PR #373.
