### ISSUE TITLE
AWS::EC2::SecurityGroup Documentation

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#379]
The examples here use localhost (127.0.0.1/32) for examples to remove default which I think is misleading because they shouldn't need outbound rules explicitly set to 127.0.0.1/32.

Should this be changed to use other addresses (a RFC 1918 10.0.0.0/8 address seems to make sense here).

**Comment by julieso** [comment]
Apologies for the delayed response. That's correct, you don't need to add a rule to allow this traffic. The purpose of this egress rule is to remove the default egress rule which allows all outbound traffic on all ports. So it effect it simply denies the traffic that would have been allowed by the default egress rule.
