### ISSUE TITLE
AWS::CodePipeline::Pipeline ActionDeclaration Configuration needs more detail

### ISSUE THREAD

**Issue by hwatts** [awsdocs/aws-cloudformation-user-guide#380]
I feel there's insufficient information in this documentation to understand what you can and can't put in the configuration section.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html#cfn-codepipeline-pipeline-stages-actions-configuration currently has this:

```
Configuration
The action declaration's configuration.

Required: No

Type: Json

Update requires: No interruption
```

If you click through several links that aren't obvious from ActionTypeId, you can eventually get to some Codepipeline documentation which gives this as the entirety of the Cloudformation action type documentation:

```
The following example shows a valid configuration for a deploy action that uses AWS CloudFormation:

"configuration": { 
    "StackName": "Name",
    "ActionMode": "Name",
    "RoleArn": "ARN", 
    "TemplateConfiguration": "Name",
    "TemplatePath": "Path" } 
```

This doesn't further define any fields. I eventually found this through Googling, which does contain the required information:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-action-reference.html

I think this, and equivalents for the other action types, should be directly linked from the CFN documentation under the correct section.

The root AWS::CodePipeline::Pipeline doc should also include working examples for all the action types, not just the handful it does currently.

**Comment by darlaker** [comment]
Hello, Thank you for commenting on the CodePipeline docs for CloudFormation! So sorry for the frustration you experienced with the incomplete action type information and examples. We are working to update this section with more links and examples. Also, I agree that more fields still need to be defined and examples provided. We will get this fixed and post the update soon. Thank you again for helping us to improve the docs!

**Comment by darlaker** [comment]
Thank you again for pointing out this issue and for helping us to improve the doc experience with this topic! 

To address your concerns, we have made the following corrections:
 
•  To provide more Configuration Property examples, in the Configuration Properties Reference (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-action-reference.html), in the JSON Object sections for Parameter Overrides and Capabilities, new example template snippets (JSON/YAML) have been provided.
•  To help the user find examples of CloudFormation configuration properties for CodePipeline, links have been added that point to the Configuration Properties Reference (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-action-reference.html), and to the template snippets examples in Using Parameter Override Functions with CodePipeline Pipelines (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-parameter-override-functions.html). The links that point to these topics have been added to the following guides:
      •	The CloudFormation User Guide, on the pipeline ActionDeclaration page (https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-properties-codepipeline-pipeline-stages-actions.html)
      •	The CodePipeline User Guide, in the Pipeline Structure Reference (footnote 5) (https://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements)
      •	The CodePipeline API Guide, on the ActionDeclaration page (https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_ActionDeclaration.html)
 
Additionally, there is a separate effort underway to provide a comprehensive set of examples for the Action Configuration fields for all provider types. 

For easier reference, below is the content that was added specifically to this page - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-action-reference.html :
"
For the list of configuration properties for the AWS CloudFormation action type in CodePipeline, see Configuration Properties Reference in the AWS CloudFormation User Guide. For template snippets with examples, see Using Parameter Override Functions with CodePipeline Pipelines in the AWS CloudFormation User Guide.

The values can be represented in either JSON or YAML format. For example, the JSON configuration item format is as follows:

JSON:

"Configuration" : { Key : Value }, 
"
