### ISSUE TITLE
AWS::DMS::Endpoint parameters marked as not required but they are mandatory

### ISSUE THREAD

**Issue by bksarthak** [awsdocs/aws-cloudformation-user-guide#381]
Port, ServerName, and Username fields are marked as not required but the CFN rollsback if you don't specify them. Hence they should be marked as mandatory/required in the docs

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
