### ISSUE TITLE
AWS::RDS::OptionGroup - Need to mention delay when deleting OptionGroup

### ISSUE THREAD

**Issue by acpucio** [awsdocs/aws-cloudformation-user-guide#383]
Hello,

When deleting CloudFormation stacks that provision RDS resources,  sometimes the stack deletion fails with the error: 

"The option group 'xyz' cannot be deleted because it is in use."

This is because there are some internal process that are working with the option group.  Eventually, the workflows or processes completes.  When this happens the user can then delete the OptionsGroup either through RDS console, CLI, or SDK.  

It would nice if we could document this behavior under AWS::RDS::OptionGroup in the CFN guide.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
