### ISSUE TITLE
AWS::RDS::DBCluster doesn't mention CopyTagsToSnapshots

### ISSUE THREAD

**Issue by michaelieti** [awsdocs/aws-cloudformation-user-guide#384]
There's no mention of copying tags to snapshots for Aurora database clusters (even though there is a reference to this in AWS::RDS::DBInstance, under the CopyTagsToSnapshots field). 

This should be amended if the capability to specify CopyTagsToSnapshots for DBCluster via Cloudformation is available.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
