### ISSUE TITLE
AWS::ECS::TaskDefinition ContainerDefinitions is required (doc says its not)

### ISSUE THREAD

**Issue by anishkny** [awsdocs/aws-cloudformation-user-guide#398]

**Comment by ckesser** [comment]
Thank you for your contribution! The "Type", "Required", "and "Update behavior" fields for each property are now auto-generated from the [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). I've submitted a ticket to correct this value in the resource spec. The [source documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html) will be updated after the specification is updated. Feel free to keep in touch here.
