### ISSUE TITLE
Missing CFN Resource Spec File Links for GovCloud (us-gov-west-1, us-gov-east-1)

### ISSUE THREAD

**Issue by ScriptAutomate** [awsdocs/aws-cloudformation-user-guide#426]
Similar to what is referenced in #320 but also for:

- `us-gov-west-1`
- `us-gov-east-1`

These should exist here:

* [AWS CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html)
  * [Source Code in This Repo](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/cfn-resource-specification.md)

The download locations can be found in `cfn-python-lint` (thanks to @PatMyron for the find and reference in another issue conversation):
- [aws-cloudformation/cfn-python-lint/src/cfnlint/maintenance.py](https://github.com/aws-cloudformation/cfn-python-lint/blob/4767ceefd5091a48fe2cb75f5954820aa150aa6b/src/cfnlint/maintenance.py#L31-L53)

**Comment by PatMyron** [comment]
@ajmay-aws should be `us-gov-west-1` and `us-gov-east-1` instead of `gov-us-west-1` and `gov-us-east-1`

**Comment by ScriptAutomate** [comment]
> @ajmay-aws should be `us-gov-west-1` and `us-gov-east-1` instead of `gov-us-west-1` and `gov-us-east-1`

Looks like they were adding and spelling was fixed on the download page. Closing.

**Comment by ScriptAutomate** [comment]
I closed this too early. The documentation / links have been updated on the official website, but they have not been updated in this repository. I will keep this open until the repository reflects the website.

It looks like the website had been updated ~20 - 22 days ago, but that this repository never was.

**Comment by ckesser** [comment]
File is now up-to-date in this repo. Thanks, @ScriptAutomate and @PatMyron!
