### ISSUE TITLE
Specification for "AuthorizerCredentials" property of "AWS::ApiGateway::Authorizer" resource is ambiguous.

### ISSUE THREAD

**Issue by razhamma** [awsdocs/aws-cloudformation-user-guide#429]
Issue Description:
-------------------
Referencing this doc[1], it is confusing and ambiguous as it doesn't really tells, what are the required permissions or what actions need to be added in the IAM role itself. Additionally, the statement "The credentials that are required for the authorizer" doesn't mention what are these credentials and causes confusion for customers.

References:
-------------
[1] https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html#cfn-apigateway-authorizer-authorizercredentials

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
