### ISSUE TITLE
Missing AWS::EC2::VPCEndpointService ResourceType in CloudFormationResourceSpecification.json for Most Regions

### ISSUE THREAD

**Issue by ScriptAutomate** [awsdocs/aws-cloudformation-user-guide#443]
The [AWS::EC2::VPCEndpointService](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html) is missing from most of the `CloudFormationResourceSpecification.json` files.

It only exists within the following spec files: `eu-north-1`, `ap-northeast-3`, `ap-east-1`, `cn-north-1`, `cn-northwest-1`

This will mean it will be left out if any automation tools are referring to `us-east-1` as a master file for module / code generation.

```json
"AWS::EC2::VPCEndpointService": {
  "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html",
  "Properties": {
    "AcceptanceRequired": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html#cfn-ec2-vpcendpointservice-acceptancerequired",
      "PrimitiveType": "Boolean",
      "Required": false,
      "UpdateType": "Mutable"
    },
    "NetworkLoadBalancerArns": {
      "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html#cfn-ec2-vpcendpointservice-networkloadbalancerarns",
      "PrimitiveItemType": "String",
      "Required": true,
      "Type": "List",
      "UpdateType": "Mutable"
    }
  }
}
```

**Comment by PatMyron** [comment]
[`AWS PrivateLink is available in these AWS Regions: US East (N. Virginia), US East (Ohio), US West (Oregon), GovCloud (US-West), US West (N. California), EU (London), EU (Ireland), EU (Frankfurt), EU (Paris), Canada (Central), Asia Pacific (Mumbai), Asia Pacific (Seoul), Asia Pacific (Singapore), Asia Pacific (Sydney), Asia Pacific (Tokyo), South America (São Paulo), China (Beijing), operated by Sinnet, and China (Ningxia), operated by Ningxia Western Cloud Data Technology Co. Ltd. (NWCD).`](https://aws.amazon.com/about-aws/whats-new/2019/03/aws-privatelink-now-supports-access-over-vpc-peering/)

[`CloudFormation support for AWS PrivateLink is available in US East (N. Virginia), US East (Ohio), US West (Oregon), US West (N. California), Canada (Central), Asia Pacific (Mumbai), Asia Pacific (Seoul), Asia Pacific (Singapore), Asia Pacific (Sydney), Asia Pacific (Tokyo), EU (Frankfurt), EU (Ireland), EU (London), and South America (Sao Paulo) Regions.`](https://aws.amazon.com/about-aws/whats-new/2018/08/aws-cloudformation-now-supports-aws-privatelink-/)

[AWS PrivateLink only in the AWS GovCloud regions in the Region Table](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/)

[AWS PrivateLink pricing pages show every region except Paris](https://aws.amazon.com/privatelink/pricing/) [(Chinese pricing page)](https://www.amazonaws.cn/en/privatelink/pricing/)

**Comment by PatMyron** [comment]
I am able to successfully create `AWS::EC2::VPCEndpoint` in `us-east-1` with this template:

```yaml
Resources:
  VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: 'com.amazonaws.us-east-1.s3'
      VpcId: !Ref VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: '10.0.0.0/16'
```

**Comment by PatMyron** [comment]
`AWS::EC2::VPCEndpoint` is now in the [`us-east-1` resource specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json)

**Comment by ScriptAutomate** [comment]
@PatMyron - `AWS::EC2::VPCEndpoint` is there but not `AWS::EC2::VPCEndpointService`

- [AWS::EC2::VPCEndpoint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html)
- [AWS::EC2::VPCEndpointService](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html)

**Comment by PatMyron** [comment]
Good catch, I was suspicious about it making its way into the resource spec since your last run [here](https://github.com/ScriptAutomate/aws-cfn-resource-specs)

 Able to create `AWS::EC2::VPCEndpointService` in `us-east-1` as well with this template:

```yaml
Resources:
  VPCEndpoint:
    Type: AWS::EC2::VPCEndpointService
    Properties:
      NetworkLoadBalancerArns:
        - 'REDACTED' # created one on the EC2 console out of laziness
```

**Comment by PatMyron** [comment]
[`AWS::EC2::VPCEndpointService`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html) is now in the [`us-east-1` resource specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json)

**Comment by ScriptAutomate** [comment]
Mission complete!
