### ISSUE TITLE
AWS::Backup::BackupSelection BackupSelectionResourceType Resource:[] Doesn't Allow "*"

### ISSUE THREAD

**Issue by jamesrenaud** [awsdocs/aws-cloudformation-user-guide#446]
Documentation for AWS::Backup::BackupSelection BackupSelectionResourceType found here (https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-backup-backupselection-backupselectionresourcetype.md) indicates that the "Resources" block is an array that allows for match patterns.

Attempting to do this via CloudFormation produces the following error:

> Resource contains * (Service: AWSBackup; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 1f273792-4f55-49a5-9c84-1016d1d357e6)

Resource Reference:
```
"BackupSelection": {
            "Type": "AWS::Backup::BackupSelection",
            "DependsOn": [
                "BackupPlan",
                "BackupRole"
            ],
            "Properties": {
                "BackupPlanId": {
                    "Fn::GetAtt": [
                        "BackupPlan",
                        "BackupPlanId"
                    ]
                },
                "BackupSelection": {
                    "SelectionName": "BackupSelection",
                    "IamRoleArn": {
                        "Fn::GetAtt": [
                            "BackupRole",
                            "Arn"
                        ]
                    },
                    "Resources": [
                        {
                            "Fn::Sub": "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
                        }
                    ]
                }
            }
        }
```

It is unclear to me if this is expected to be allowed by AWS Backup - it doesn't appear as though you can use "*" for resources via the Console leading me to believe this is incorrect documentation.

The CLI documentation makes this a bit clearer:
> It includes an array of resources, an optional array of patterns to exclude resources, an optional role to provide access to the AWS service the resource belongs to, and an optional array of tags used to identify a set of resources.

This reads as though you can exclude tags via the supported conditions parameter, but not *include* them via ARN wildcards.

**Comment by alexramos1** [comment]
Is there a work-around? How can you specify all resources in an account, without having to list them one by one or tag them all?
