### ISSUE TITLE
[AWS::RDS::DBParameterGroup] No apparent way to set group name

### ISSUE THREAD

**Issue by krukru** [awsdocs/aws-cloudformation-user-guide#450]
The docs do not explain how to set "GroupName" for resource AWS::RDS::DBParameterGroup.
For example, when using the console or api this option exists. 
See https://docs.aws.amazon.com/cli/latest/reference/rds/create-db-parameter-group.html (param `--db-parameter-group-name`)
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithParamGroups.html (step 6: In the Group name box, enter the name of the new DB parameter group.)

Cloudformation auto generates a name from the Stack name, parameter group family and some random suffix string.

**Comment by krukru** [comment]
Also I noticed, as a curiosity, that AWS::RDS::DBSubnetGroup or AWS::RDS::OptionGroup have property names prefixed with their respective resource name. 
For example AWS::RDS::DBSubnetGroup has properties `DBSubnetGroupName` and `DBSubnetGroupDescription`, AWS::RDS::OptionGroup has properties `OptionConfigurations` and `OptionGroupDescription` while AWS::RDS::DBParameterGroup has `Description`. Interesting :)

**Comment by PatMyron** [comment]
Unfortunately, this is not yet supported in CloudFormation. Support is being tracked here:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/212

**Comment by vocxpo** [comment]
We also need a OptionGroupName, which is available in cli.

**Comment by bcmyguest** [comment]
@vocxpo https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-optiongroup-optionconfigurations.html#cfn-rds-optiongroup-optionconfigurations-optionname
