### ISSUE TITLE
Need clarity on setting Version property for Elastic Beanstalk environments.

### ISSUE THREAD

**Issue by jeremyjpaws** [awsdocs/aws-cloudformation-user-guide#46]
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-beanstalk-environment-tier.md

Setting the Version will often lead to production pain and abnormal Elastic Beanstalk environment behavior for modern applications. No where in AWS docs is there a detailed history of tier versions and their solution stack version compatibility. It is advised to add a note like the following:
* "Deprecated and not recommended for use. When left unspecified, the latest compatible worker tier version will be used."

**Comment by ckesser** [comment]
Thanks, @jeremyjpaws! The 'Version' property description has been updated: https://docs.aws.amazon.com/it_it/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment-tier.html. Closing the issue.
