### ISSUE TITLE
Duplication in Instance size in AWS::Redshift::Cluster

### ISSUE THREAD

**Issue by keroloswilliam** [awsdocs/aws-cloudformation-user-guide#486]
I have found duplication in NodeType in AWS::Redshift::Cluster [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-nodetype) 

`Valid Values: ds2.xlarge | ds2.8xlarge | ds2.xlarge | ds2.8xlarge | dc1.large | dc1.8xlarge | dc2.large | dc2.8xlarge`

as you can see that ds2.xlarge is duplicated 

I would have opened a PR but I don't know all the instance sizes

**Comment by mjalkio** [comment]
The listed node types are the full list, they're described on the page that's linked to. I opened a PR to fix this.

**Comment by ckesser** [comment]
Thanks @keroloswilliam and @mjalkio! Closing this Issue in favor of PR #503.
