### ISSUE TITLE
Is StreamEncryption really a 'Required' property?

### ISSUE THREAD

**Issue by rk-yen** [awsdocs/aws-cloudformation-user-guide#5]
Ref: https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-kinesis-stream.md

The latest doc updates refers to StreamEncryption as a _Required_ property. Is that indeed the case? We recently tried to create a Kinesis Stream without this property set, and it went through fine. Can someone please clarify this?

Thanks.

**Comment by PatMyron** [comment]
Had the same experience with it working without that property. Made a pull request here: https://github.com/awsdocs/aws-cloudformation-user-guide/pull/12

**Comment by AWSRandall** [comment]
Hey, thanks for using CloudFormation!

I just checked the source. And although EncryptionType and KeyId are both required, StreamEncryption itself does not appear to be required. I'll update and push later today.

Thanks for reporting this issue!

**Comment by PatMyron** [comment]
Merged in now, feel free to close

**Comment by rk-yen** [comment]
Thank you.
