### ISSUE TITLE
How to add cc in verification mail

### ISSUE THREAD

**Issue by krishnappahuded** [awsdocs/aws-cloudformation-user-guide#506]
Is it possible to add CC in no-replay verification mail generated by the  Cognito User Pool SignUp method. Please help me to achieve this.

**Comment by rachfop** [comment]
Hello @krishnappahuded thank you for your feedback. I would suggest that you try the AWS Forums for case specific questions: https://forums.aws.amazon.com/forum.jspa?forumID=92
