### ISSUE TITLE
AWS CloudFormation limit update

### ISSUE THREAD

**Issue by taraslayshchuk** [awsdocs/aws-cloudformation-user-guide#512]
To have all things in a same place. Could you please add information about [stack_name length limit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-using-console-create-stack-parameters.html#cfn-using-console-create-stack-parameters-awstypes) and [tags name|value length limit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html#w2ab1c21c10d212c13c17) into [AWS CloudFormation limits](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/cloudformation-limits.md)?

**Comment by PatMyron** [comment]
[Output description length limit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html)
and 1000 Change Sets per CloudFormation stack version as well

**Comment by taraslayshchuk** [comment]
Nice! Well done! Great job! Thanks! @rachfop @PatMyron What about [tags name|value length limit](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html#w2ab1c21c10d212c13c17)?
