### ISSUE TITLE
minimum permissions claim or example policy should be revised to conform with least priviledge

### ISSUE THREAD

**Issue by FireballDWF** [awsdocs/aws-cloudformation-user-guide#530]
UserGuide/stacksets-prereqs.html claims that "The following example shows a policy statement with the minimum permissions for StackSets to work", however allowing it to read and write to every s3 bucket can't possibly be consistent with "minimum permissions" aka "least priviledge".  Please revise the policy to only include the s3 actions and buckets that are actually required.  Same thing with sns, does it really need all actions, even CheckIfPhoneNumberIsOptedOut ?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
