### ISSUE TITLE
Brief Description on Pre-requisites when deploying StackSets accross an Organizational Unit.

### ISSUE THREAD

**Issue by razhamma** [awsdocs/aws-cloudformation-user-guide#533]
Description:
--------------
The doc here[1](including sub nodes) does not actually mention anything on Pre-requisites when deploying StackSets accross an Organizational Unit, where "StackSets across an Organizational Unit are only recommended to be created via Master/Root Account in an AWS Organization(due to AWS Organizations APIs' organization wide nature." being the top most pre-req.

This causes confusion for customers and they face different errors when trying to deploy StackSet within a child account. 

References:
-------------
[1] Working with AWS CloudFormation StackSets - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/what-is-cfnstacksets.html

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
