### ISSUE TITLE
Deployment type should be required in Documentation in AWS::CodeDeploy::DeploymentGroup DeploymentStyle

### ISSUE THREAD

**Issue by keroloswilliam** [awsdocs/aws-cloudformation-user-guide#534]
As mentioned in this [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-codedeploy-deploymentgroup-deploymentstyle.html#cfn-codedeploy-deploymentgroup-deploymentstyle-deploymenttype) defining DeploymentOption and DeploymentType Is Not Required 
But After Defining DeploymentType to be IN_PLACE for 2 instances I got the Error 
```
Deployment type or deployment option cannot be null or empty 
``` 
So DeploymentType can not be Null make sense since i have to choose the type and there is no default mentioned in any place 

but DeploymentOption should accept null since i can deploy without being behind load balance Also if you are working with console you won't find that option when choosing IN_PLACE as Deployment Type 

I have already reached the support to open internal bug and this Issue just to clarify

**Comment by ckesser** [comment]
Closing per #536

**Comment by QasimArthuna53** [comment]
I had the same problem, and I couldn't able to solve it.
this is my codedeploy target

`DeploymentStyle: 
        DeploymentType: IN_PLACE
        DeploymentOption: Yes`

but this throws this error 

`Deployment option can only be WITH_TRAFFIC_CONTROL or WITHOUT_TRAFFIC_CONTROL`

Help will be appreciated.

Thank you
