### ISSUE TITLE
Loading cfn-response using nodejs10.x

### ISSUE THREAD

**Issue by RLThomaz** [awsdocs/aws-cloudformation-user-guide#538]
As requested by AWS Lambda operational team, users should update their lambda functions from previous versions to NodeJs 10.x. However, it seems that loading the module `cfn-response` requires a relative path location, thus we must `require('./cfn-response')`. Please refer to aws/aws-sdk-js#2955 for more information.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
