### ISSUE TITLE
Cloudformation AWS::FSx::FileSystem template is wrong

### ISSUE THREAD

**Issue by stanfan1992** [awsdocs/aws-cloudformation-user-guide#541]
in the template you provided with wrong property name, in: WindowsConfiguration-> Username , should be UserName. Please check the link.
AWS::FSx::FileSystem - Create an Amazon FSx for Windows File Server File System in a Self-managed Active Directory  - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html#aws-resource-fsx-filesystem--examples--Create_an_Amazon_FSx_for_Windows_File_Server_File_System_in_a_Self-managed_Active_Directory

I am trying to make a pull request. However, the document and the aws-resource-fsx-filesystem.md file doesn't match. So I raisied the issue.

**Comment by rachfop** [comment]
Hello, thank you for your contribution. It looks like this issue is fixed so I am going to close it.
