### ISSUE TITLE
Encountered unsupported property KmsKeyId

### ISSUE THREAD

**Issue by codetinkerhack** [awsdocs/aws-cloudformation-user-guide#543]
I am attempting to create an ECS cluster from ECS optimised AMI Linux 2. According to docu I can use CMK to create encrypted volume:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-blockdev-template.html

And according to this doco this should be possible to create encrypted root volume from shared unencrypted AMIs:

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIEncryption.html

My CFN: 

```  ECSLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: !Ref EcsAmi
      InstanceType: !Ref InstanceType
      InstanceMonitoring: true
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            DeleteOnTermination: true
            VolumeSize: !Ref EC2RootVolumeSize
            VolumeType: gp2
            Encrypted: true
            KmsKeyId: !Ref KmsKeyId
```

I get following error:

ECSLaunchConfiguration	UPDATE_FAILED	Encountered unsupported property KmsKeyId

**Comment by codetinkerhack** [comment]
As per response from AWS. This option apparently not supported on Auto Scaling Groups : Launch configuration
and only supported on  "AWS::EC2::Instance" directly.

**Comment by Reneehi** [comment]
Hi, If you use a launch template, you also have the option of specifying a KmsKeyId. For more information, see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-blockdevicemapping-ebs.html and https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-template.html.
