### ISSUE TITLE
UserPoolClient allowedOAuthFlows has incorrectly documented allowed values.

### ISSUE THREAD

**Issue by thantos** [awsdocs/aws-cloudformation-user-guide#563]
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-cognito-userpoolclient.md
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-allowedoauthflows

Documentation says `code` or `token` is allowed. On giving `['code', 'token']` I received the error:

```
coreUserPoolClient 1 validation error detected: Value '[code, token]' at 'allowedOAuthFlows' failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [implicit, client_credentials, code]] (Service: ...; Status Code: 400; Error Code: InvalidParameterException; Request ID: 3ad6f5bf-6822-4867-86b7-dd8768f2ee01)
```

On updating to the `['client', 'implicit']` the stack update passed.

I imagine the documentation should be updated to reference `code`, `implicit`, and `client_credentials`?

**Comment by thantos** [comment]
Similar issue #564

**Comment by julieso** [comment]
Thanks for pointing this out. I merged the pull request.
