### ISSUE TITLE
UserPoolClient allowedOAuthScopes has incorrectly documented allowed values.

### ISSUE THREAD

**Issue by thantos** [awsdocs/aws-cloudformation-user-guide#564]
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-cognito-userpoolclient.md
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#cfn-cognito-userpoolclient-allowedoauthscopes

Documentation says `Cognito` is allowed. On giving `['Cognito', ... more values and a custom scope ... ]` I received the error:

```
coreUserPoolClient Invalid scope requested: Cognito (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: ScopeDoesNotExistException; Request ID: 865b2250-1f4a-4b27-ae35-ce2839e56533)
```

On updating to the `['profile', ... same as before ... ]` the stack update passed.

I imagine the documentation should be updated to reference `profile` and `Cognito` should be removed?

**Comment by thantos** [comment]
Similar issue: #563

**Comment by julieso** [comment]
Thanks for pointing this out. I've merged the pull request.
