### ISSUE TITLE
AWS::Events::Rule missing EventBusName property

### ISSUE THREAD

**Issue by razhamma** [awsdocs/aws-cloudformation-user-guide#567]
AWS::Events::Rule resource supports EventBusName property - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventbusname 

This Property is not listed here - https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-events-rule.md

Please update.

**Comment by PatMyron** [comment]
`EventBusName` is now present in [this repository](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-events-rule.md)

[The general problem of this repository lagging the live documentation is being tracked here](https://github.com/awsdocs/aws-cloudformation-user-guide/issues/428)
