### ISSUE TITLE
feature request specify Amazon SNS event destinations in CloudFormation templates.

### ISSUE THREAD

**Issue by aleon1220** [awsdocs/aws-cloudformation-user-guide#576]
for the page [AWS::SES::ConfigurationSetEventDestination](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-configurationseteventdestination.html) there should be a feature that allows to specify the ARN of an AWS SNS topic.

This feature should validate that the SNS topic is created before hand or specified in the documentation.

This is very useful when streaming AWS SES events to AWS SNS and from there to third parties or AWS CloudWatch logs.

My use case is:
a bitbucket account with AWS IaaC. Every environment (dev, QA, test) is an AWS account and there is an automated step to create the whole AWS infrastructure).
Finally when the AWS SES and SNS stacks are created they should be visualized in DataDog.

Unfortunately not having this feature to setting the SNS topic as the event destination requires extra manual and documented steps.

Thank you

**Comment by aleon1220** [comment]
@aetter does this help in any way for aws improvements?

**Comment by tvb** [comment]
How can we move forward with this story?

**Comment by jyeagle** [comment]
It would be nice to get this done.  I am wiring SES events to SNS topics today via Cloud Formation and I was surprised to find out that AWS has not implemented this yet!

I will be waiting on it!

**Comment by aleon1220** [comment]
> How can we move forward with this story?
> 
> @aleon1220 can you forward this to https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap ?

honestly too much effort for me for a company that makes billions.
Maybe if AWS gives me credit to complete my AWS EKS training I would do it.

**Comment by tvb** [comment]
I just meant there is another board for feature requests in regards of CloudFormation support.

**Comment by gabegorelick** [comment]
This is tracked at https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/50.

**Comment by aleon1220** [comment]
> This is tracked at [aws-cloudformation/cloudformation-coverage-roadmap#50](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/50).

great

**Comment by aleon1220** [comment]
It seems that the roadmap item 50 [aws-cloudformation/cloudformation-coverage-roadmap#50](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/50) implemented this. Is ready at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ses-configurationseteventdestination-snsdestination.html
