### ISSUE TITLE
ELB ForrwardConfig section missing

### ISSUE THREAD

**Issue by tvddhi** [awsdocs/aws-cloudformation-user-guide#578]
Hi,
on the page [https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-elasticloadbalancingv2-listenerrule-actions.md](url) the section ForwardConfig is missing 
It's described https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html
Thanks

**Comment by julieso** [comment]
Hello. The documentation is generated from the resource specification. This property is not yet included in the resource specification. The documentation will be updated after the resource specification is updated.
