### ISSUE TITLE
Glue jobs with connections list fails

### ISSUE THREAD

**Issue by charliejllewellyn** [awsdocs/aws-cloudformation-user-guide#582]
Hi, the docs for creating Glue jobs with CloudFormation state a list of strings should be provided to add connections to the jobs e.g.

```  
MyJob1:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: "s3://aws-glue-scripts-xxxxxxxxxxxx-eu-west-2/admin/test"
      Connections:
        - connectionName
      GlueVersion: 1.0
      ExecutionProperty:
        MaxConcurrentRuns: 2
      MaxRetries: 0
      Name: DemoCf1
      Role: !Ref MyJobRole
```

Doing this errors with:

Property validation failure: [Value of property {/Connections} does not match type {Object}]

The docs for a connections list are here https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-glue-job-connectionslist.md.

What is the correct way to provide a list of connections for Glue to use with jobs?

**Comment by ttres** [comment]
Hi @charliejllewellyn. Not sure you still needs this, but I've managed to replicate your issue.
To fix it, you should add a second level `Connections` element, like this:

```yaml
      Connections:
        Connections:
          - connectionName
```

The first `Connections` is for AWS::Glue::Job resource, and the second one is for [ConnectionsList](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-job-connectionslist.html
).

Another suggestion is to transform Glue version in a string, like this: `GlueVersion: "1.0"`. This is not required, but will ensure [CloudFormation Linter](https://github.com/aws-cloudformation/cfn-python-lint) passes.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
