### ISSUE TITLE
CodePipeline does not return ARN

### ISSUE THREAD

**Issue by meap** [awsdocs/aws-cloudformation-user-guide#596]
I want to connect CodeStar notification rule to Pipeline, where ARN is needed as a resource value, but the pipeline does not return ARN.

I have to do manually by concatenating string which is not good.

```
  PipelineNotificationRule:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: FULL
      Name: !Sub '${AWS::StackName}-notification-rule'
      Resource: !Sub "arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}-pipeline"
      Status: ENABLED
```

Is there a better way? I guess the pipeline should return ARN in return values.

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/376
