### ISSUE TITLE
Properties of resources

### ISSUE THREAD

**Issue by miparnisari** [awsdocs/aws-cloudformation-user-guide#602]
On the [Resources user guide](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/resources-section-structure.md) it says this:

> Property values can be literal strings, lists of strings, Booleans, parameter references, pseudo references, or the value returned by a function.

This is not very clear. Properties can also be plain JSON objects or arrays of objects, e.g.

```json5
"Resources": {
    "DetectTextInImage": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": { // object
          "S3Bucket": "cfnrjl-resources",
          "S3Key": "35f0a1aaabb6bbfa67bfcc016dfffbb3"
        }
    },
    "InstanceSecurityGroup" : {
      "Type" : "AWS::EC2::SecurityGroup",
      "Properties" : {
        "SecurityGroupIngress" : // array of objects
          [ { "IpProtocol" : "tcp", "FromPort" : "22", "ToPort" : "22", "CidrIp" : { "Ref" : "SSHLocation"} }]
      }

}

```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
