### ISSUE TITLE
Nested stacks documentation is not great

### ISSUE THREAD

**Issue by miparnisari** [awsdocs/aws-cloudformation-user-guide#603]
Feedback on [this](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/using-cfn-nested-stacks.md) page: it's not clear.

- how do you pass data from the parent to a nested stack? Are parameters the only way? (Judging by https://www.linkedin.com/pulse/aws-cloudformation-passing-parameters-nested-stacks-murdock/, the answer is yes but i'm not sure)
- on a similar note, how do updates work? if I change a parent stack will the child "see" the changes? likewise, if I update a child stack, when will the parent "see" the changes, if ever?
- how do nested stacks affect limits? quoting a question from the comments [here](https://aws.amazon.com/blogs/devops/use-nested-stacks-to-create-reusable-templates-and-support-role-specialization/): "As it relates to AWS Stack Limits (which I noticed is 200 by default) does a nested stack count as a single stack, or will each nested stack within the top-level stack be counted towards the stack limit of 200?"

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
