### ISSUE TITLE
AWS::IoT::TopicRule FirehoseAction needs note for allowed values in YAML

### ISSUE THREAD

**Issue by BetterBenWorseBen** [awsdocs/aws-cloudformation-user-guide#604]
Separator

    A character separator that will be used to separate records written to the Firehose stream. Valid values are: '\n' (newline), '\t' (tab), '\r\n' (Windows newline), ',' (comma). 

The above is correct for JSON but if used in YAML it gets converted incorrectly. For example, if the YAML template uses '\n' or \n it gets converted to "\\n" in JSON which is invalid.

There should be a note that says for YAML the values need to be encased by double quotes to work properly.

**Comment by asavila** [comment]
I have applied a fix for this that will go live on 8/13 as part of the new AWS::IoT::Authorizer resource launch.
