### ISSUE TITLE
Minor: formatting issue in JSON template

### ISSUE THREAD

**Issue by miparnisari** [awsdocs/aws-cloudformation-user-guide#607]
On this page: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html#intrinsic-function-reference-getatt-examples

The JSON example given looks weird: 
![image](https://user-images.githubusercontent.com/5374887/75379166-c9f10080-5889-11ea-8dae-35507b749eb4.png)

Look at the syntax highlighting, it's as if it's not recognizing it's JSON.

I wonder why the source code uses

     ```


instead of ```json?

**Comment by PatMyron** [comment]
Seeing this on [other pages](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html) as well:

<img width="533" alt="Screen Shot 2020-03-11 at 4 48 31 PM" src="https://user-images.githubusercontent.com/7014355/76474278-5a662f80-63b8-11ea-9674-34c6c3d0fb16.png">

**Comment by rachfop** [comment]
The GetAtt page will be updated in the next doc release and @PatMyron I have submitted a ticket against API Gateway docs. Thank you all for your contributions.
