### ISSUE TITLE
Documentation requires resource to be added to policy that isn't a valid arn

### ISSUE THREAD

**Issue by snoble** [awsdocs/aws-cloudformation-user-guide#608]
On this line https://github.com/awsdocs/aws-cloudformation-user-guide/blame/master/doc_source/using-iam-template.md#L121 it says to include permission on the resource `arn:aws:cloudformation:<region>:aws:transform/Serverless-2016-10-31`. However this is reported to be an unrecognized resource type in the console. 
![image](https://user-images.githubusercontent.com/57576/75594131-92768580-5a3c-11ea-9644-520e59ae5b2a.png)

It can still be submitted if you edit the json but it will not be accepted if you use the guided tool.

**Comment by rachfop** [comment]
Hello @snoble. Thank you for your contribution to the docs. This error could be showing up for a few reasons. You might have two factor authentication turned on or you might be deploying it in another region than the one you have listed. To learn more about Amazon Resource Names, see [here](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)
If this trouble persists please feel free to open a PR or another issue.
