### ISSUE TITLE
EgressOnlyInternetGateway Does Not Support the Tags Property

### ISSUE THREAD

**Issue by Pheric** [awsdocs/aws-cloudformation-user-guide#610]
According to the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-egressonlyinternetgateway.html), Egress-Only Internet Gateways do not support the Tags property in CloudFormation. Attempting to include the property results in an error: "Encountered unsupported property Tags." However, tags can be added in the web console without issue, and are at least readable using the API (via the Go SDK). Is this property supported?

**Comment by PatMyron** [comment]
merging into the issue for [resource type tagging coverage requests](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/228)
