### ISSUE TITLE
AWS::AutoScaling::AutoScalingGroup typo in yaml syntax on the website only

### ISSUE THREAD

**Issue by j2clerck** [awsdocs/aws-cloudformation-user-guide#62]
Hello,

I've spotted a typo on the yaml syntax for the AutoScalingGroup having an extra quote on the LaunchTemplate parameter. However I cannot find it on the git to change it myself, otherwise I would have.

`LaunchTemplate" : LaunchTemplateSpecification`

Regards,
Joseph

**Comment by ckesser** [comment]
@j2clerck Thank you for bringing this to our attention! I merged PR #114 to address this typo, so I'm going to go ahead and close this issue.
