### ISSUE TITLE
Latest version information missing from aws-cfn-bootstrap "Release History" page

### ISSUE THREAD

**Issue by andyspiers** [awsdocs/aws-cloudformation-user-guide#620]
For installing aws-cfn-bootstrap from a .tar.gz file, this document recommends using "latest":
  https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/cfn-helper-scripts-reference.md

We were investigating a bug logging Unicode so wanted to compare "latest" with the latest published version as mentioned on the "Release History" page here:
  https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/releasehistory-aws-cfn-bootstrap.md

The latest _published_ version is 1.4.30 but if I download "latest" from https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz then it has a number of **different files** when compared to 1.4.30. Also, "latest" contains files modified on 2018-08-16  compared to 2018-03-14 for version 1.4.30

I tried to guess the URL of a newer version  of aws-cfn-bootstrap and I found that 1.4.31 seems to exist and has exactly the same hash as "latest" but is not listed in the release history.

Can you please update the release history with details of this latest version which appears to be 1.4.31?

Thanks,
Andy Spiers

**Comment by PatMyron** [comment]
Confirmed `1.4-31` is the latest version by [downloading](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-helper-scripts-reference.html), unzipping, and grep'ing the source:

```shell
$ grep -r '1\.4-' aws-cfn-bootstrap-1.4/
aws-cfn-bootstrap-1.4//cfnbootstrap/public_constants.py:_version = '1.4-' + _release

$ grep -r '_release' aws-cfn-bootstrap-1.4/
aws-cfn-bootstrap-1.4//cfnbootstrap/public_constants.py:_release = '31'
aws-cfn-bootstrap-1.4//cfnbootstrap/public_constants.py:_version = '1.4-' + _release
```

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
