### ISSUE TITLE
InviteMessageTemplate on AWS::Cognito::UserPool

### ISSUE THREAD

**Issue by yashutanna** [awsdocs/aws-cloudformation-user-guide#621]
Hey guys

Im trying to figure out how to get the the invitation message that i have to manually set in AWS console to stick whenever my stack is updated. 

I see there is documentation on updating InviteMessageTemplate
![image](https://user-images.githubusercontent.com/6696871/76603541-cf9b4700-6515-11ea-8b62-b9ba63fc8562.png)

but I'm unable to actually use this using cloudformation. 

![image](https://user-images.githubusercontent.com/6696871/76603608-ee99d900-6515-11ea-888a-4b885b34607a.png)

Please help?

**Comment by jeanverster** [comment]
@yashutanna and for anyone else looking to customise the default Cognito templates, you're able to overwrite the default html being used via cognito lambda triggers. In particular, the Custom Message Lambda Trigger:

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-custom-message.html

Your lambda will receive an event with a `triggerSource` property which contains the specific cognito event source. You can then inject an html template string with your own custom html, just remember to include `{####}` somewhere  for cognito to replace with the auth code in question. 

Here's an example of what your handler might look like:

```
import { AdminCreateUser, ResendCode, ResetPassword, VerifyEmail } from './templates'
exports.handler = (event, context, callback) => {
  switch (event.triggerSource) {
    case 'CustomMessage_SignUp':
      event.response.emailMessage = VerifyEmail
      break
    case 'CustomMessage_ResendCode':
      event.response.emailMessage = ResendCode
      break
    case 'CustomMessage_AdminCreateUser':
      event.response.emailMessage = AdminCreateUser
      break
    case 'CustomMessage_ForgotPassword':
      event.response.emailMessage = ResetPassword
    default:
      break
  }
  callback(null, event)
}
```  

Hope this helps!

**Comment by danPudwellUK** [comment]
Maybe a bit late but you can do this in CloudFormation under
AWS::Cognito::UserPool AdminCreateUserConfig
