### ISSUE TITLE
default nodejs4.3 runtime version is outdated

### ISSUE THREAD

**Issue by Norbinsh** [awsdocs/aws-cloudformation-user-guide#635]
The cloudformation [template](https://s3.amazonaws.com/cloudformation-examples/lambda/LambdaAMILookupSample.template) in [this userguide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/walkthrough-custom-resources-lambda-lookup-amiids.html) comes with a nodejs runtime of 4.3 which can no longer be used and is leading to a deployment failure.
Please update the runtime there from "nodejs4.3" to "nodejs10.x" or even better "nodejs12.x"

**Comment by mwunderl** [comment]
Created https://github.com/awsdocs/aws-cloudformation-user-guide/pull/669 for the guide update.

**Comment by rachfop** [comment]
Thank you @Norbinsh for pointing this out. @mwunderl has created a PR which will be merged in  the next build.
