### ISSUE TITLE
Examples clearer using Fn::Sub rather than Fn::Join?

### ISSUE THREAD

**Issue by helloPiers** [awsdocs/aws-cloudformation-user-guide#640]
Just a thought, maybe the exampes could be clearer (by being shorter - fitting easier on one screen, etc) by using intrinsic "Fn::Sub" in place of "Fn::Join" (for YAML, !Sub vs !Join)?

For example (from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigatewayv2-integration.html):
```
 "IntegrationUri": {
                "Fn::Join": [
                    "",
                    [
                        "arn:",
                        {
                            "Ref": "AWS::Partition"
                        },
                        ":apigateway:",
                        {
                            "Ref": "AWS::Region"
                        },
                        ":lambda:path/2015-03-31/functions/",
                        {
                            "Ref": "MyLambdaFunction"
                        },
                        "/invocations"
                    ]
                ]
            },
``` 
could be written as 
```
"IntegrationUri": {
  "Fn::Sub": "arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction}/invocations"
}
```

**Comment by helloPiers** [comment]
It's a separate thing, really, but when I get-integration from the apigatewayv2 CLI, for an integration I created manually via console, the IntegrationUri doesn't have /invocations on the end.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
