### ISSUE TITLE
CaseSensitive support documentation not updated

### ISSUE THREAD

**Issue by ethanabowen** [awsdocs/aws-cloudformation-user-guide#641]
The file aws-cloudformation-user-guide/doc_source/**aws-properties-cognito-userpool-usernameconfiguration.md** is out of date from the actual implementation.

![image](https://user-images.githubusercontent.com/1947151/78074673-c0ffbd00-7368-11ea-9033-0111186d88b4.png)

Although the website shows that CaseSensitive is NOT supported, my team and I have tested it and it IS in fact now supported (as of a few weeks ago I believe).

**Comment by PatMyron** [comment]
[`AWS::Cognito::UserPool.UsernameConfiguration` documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html) updated

> The file aws-cloudformation-user-guide/doc_source/**aws-properties-cognito-userpool-usernameconfiguration.md** is out of date from the actual implementation.

Tracking this issue in https://github.com/awsdocs/aws-cloudformation-user-guide/issues/428
