### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by mcalr3** [awsdocs/aws-cloudformation-user-guide#656]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-instancemarketoptions-spotoptions.html

On the above page, the link under
`SpotOptions is a property of the Amazon EC2 LaunchTemplate InstanceMarketOptions property type.`

Appears to be broken.

**Comment by rachfop** [comment]
Thank you for you find! The link you are looking for can be found here: 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-instancemarketoptions.html

I have made the changes per your suggestion and they will be committed soon.
