### ISSUE TITLE
Please add "ServiceRegistries" attribute in AWS::ECS::Service

### ISSUE THREAD

**Issue by SHLo** [awsdocs/aws-cloudformation-user-guide#66]
Service discovery is now supported in ECS. https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html

Although this document has not been updated yet, adding "ServiceRegistries" property in AWS::ECS::Service is working.  The schema of this property is an array of single key "RegistryArn" object.

For example:

Properties:
    ServiceRegistries:
        - RegistryArn: "arn:aws:servicediscovery:xxxxx:xxxxx:service/xxxxx"

**Comment by jeshan** [comment]
This has since been updated

**Comment by orbang** [comment]
The containerName and containerPort properties seem to be missing.

**Comment by orbang** [comment]
Any chance to add the two missing properties (containerName and containerPort)? See https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ServiceRegistry.html

**Comment by ckesser** [comment]
Apologies for the late response! CloudFormation added support for 'ContainerName' and 'ContainerPort' on September 20: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html. Thank you all for engaging with this issue. I'm going to go ahead and close this out.
