### ISSUE TITLE
Description of DeploymentId property of AWS::ApiGateway::Stage is incorrect

### ISSUE THREAD

**Issue by dkamenov-df** [awsdocs/aws-cloudformation-user-guide#662]
The description of `DeploymentId` on [this page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html#cfn-apigateway-stage-deploymentid) has a contradiction. It seems the property is indeed required

```
DeploymentId
The ID of the deployment that the stage is associated with. This parameter is required.

Required: No

Type: String

Update requires: No interruption
```

**Comment by PatMyron** [comment]
Sorry about that, and thank you for your contribution! This should be required, but the `Type`, `Required`, and `Update behavior` fields for each property are auto-generated from the [CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). The [source documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-stage.html#cfn-apigateway-stage-deploymentid) will be updated after the specification is corrected:
#440
#478
#551
#574
#577
#617
#625
#627
https://github.com/awsdocs/aws-cloudformation-user-guide/pull/630
