### ISSUE TITLE
Need an example for this instruction on subproperties

### ISSUE THREAD

**Issue by irfaanz** [awsdocs/aws-cloudformation-user-guide#702]
Hello,

I am just trying to understand how do i provide the details in this "ResourceLabel
Identifies the resource associated with the metric type. You can't specify a resource label unless the metric type is ALBTargetGroupRequestCount and there is a target group for an Application Load Balancer attached to the Auto Scaling group.

The format is app/<load-balancer-name>/<load-balancer-id>/targetgroup/<target-group-name>/<target-group-id>, where:

app/<load-balancer-name>/<load-balancer-id> is the final portion of the load balancer ARN.

targetgroup/<target-group-name>/<target-group-id> is the final portion of the target group ARN."

The background situation is i am creating a stack with ASG and target groups in it and i am adding scaling policy as a resource. I am digging to see what all properties can be used in this stack. I am not sure what i need to enter here in cloudformation stack. 

I am not clear about "<load-balancer-id> is the final portion of the load balancer ARN" as i am yet to create this stack then how do i obtain the load balancer id. Please help me to understand clearly. Your help is greatly appreciated. I am just a newbie and trying to learn as much as i can. 

Irfan

**Comment by rachfop** [comment]
Hello irfaanz,

Thanks very much for taking the time to submit feedback on our documentation. It sounds like you actually have a technical support question. I suggest that you post it on the Amazon AWS CloudFormation forum, which is a good resource: https://forums.aws.amazon.com/forum.jspa?forumID=92

 You might also consider signing up for AWS technical support: https://aws.amazon.com/premiumsupport/  

 Best regards,
