### ISSUE TITLE
Docs list unsupported return values

### ISSUE THREAD

**Issue by jeshan** [awsdocs/aws-cloudformation-user-guide#703]
On the pages for `AWS::SSM::Association` and `AWS::Athena::NamedQuery`, we see that they each document a return value of NamedQueryId and AssociationId respectively.

However, they both come with the note:
```
Not currently supported by AWS CloudFormation.
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-namedquery.html#aws-resource-athena-namedquery-return-values

![image](https://user-images.githubusercontent.com/1020565/83292936-0707be80-a1fc-11ea-8662-adc924b7d898.png)

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-association.html#aws-resource-ssm-association-return-values

![image](https://user-images.githubusercontent.com/1020565/83292949-0cfd9f80-a1fc-11ea-8254-07f229fc558a.png)

I'm wondering, is there any reason for it to be documented if we can't use it yet? What purpose do they currently serve?

**Comment by rachfop** [comment]
Hello @jeshan thank you for your feedback and interests in our documentation. I have created a ticket with the writers who have "Not currently supported by AWS CloudFormation" on their attributes. Thank you again for your feedback.
