### ISSUE TITLE
Clarify what happens during updates when DependsOn is used

### ISSUE THREAD

**Issue by miparnisari** [awsdocs/aws-cloudformation-user-guide#709]
For https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-attribute-dependson.md#dependson-attribute

Can you take the information from [here](https://sage.amazon.com/questions/898654) and clarify what happens during updates?

**Comment by rachfop** [comment]
Hello @miparnisari would clarifying that both Fn::Getatt and Fn::Ref act as implicit dependencies, help clarify what happens during updates?

**Comment by miparnisari** [comment]
Yes, but i'd like to be super explicit about it. E.g. i'd like to see this change from

>  For example, if the properties of resource A use a !Ref to resource B, the following rule apply:
Resource B is created before resource A. Resource A is deleted before resource B.

to something like

>  For example, if the properties of resource A use a !Ref to resource B, the following rule apply:
Resource B is created before resource A. Resource A is deleted before resource B. Resource B is updated before resource A.

**Comment by rachfop** [comment]
Thank you for your contribution. The documents will be updated.
