### ISSUE TITLE
Improve and fix Fn::Cidr docs

### ISSUE THREAD

**Issue by xRokco** [awsdocs/aws-cloudformation-user-guide#71]
It looks like the Fn::Cidr docs is currently in a mix of being sparse and inaccurate.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-cidr.html

The docs says the sizeMask argument is optional, it is actually required. The error message the console gives when the sizeMask argument isn't included also says it's optional, despite the fact it's required.

Secondly, the explanation for the sizeMask argument is pretty unclear or complicated, so I think it should be expanded on, especially considering it is required. I would initially assume it refers to the number after the slash in a CIDR block (i.e. the 24 in 192.168.1.0/24) as I and a couple of other engineers did, but it actually refers to the number of bits to keep free/available in the CIDR block (i.e. 32 - sizeMask = the number after the slash in a CIDR range, so to make the CIDR range 192.168.1.0/24 you set sizeMask to 8). This means 2^sizeMask free IPs in the CIDR block generated function.

Ideally for me, the actual function would be changed to be simpler, but the docs should be updated in the meantime.

Cheers.

**Comment by NightKhaos** [comment]
Please see the following PR:

https://github.com/awsdocs/aws-cloudformation-user-guide/pull/49

I think this should fix the issues with the documentation, only waiting on it being merged.

**Comment by rmzi** [comment]
This was very helpful! Thanks, and hope this lands soon.

**Comment by ikben** [comment]
#49 Has been closed, so I assume this one can be closed too?
