### ISSUE TITLE
AWS::ApiGateway::Method AuthorizerId also for use with COGNITO_USER_POOLS

### ISSUE THREAD

**Issue by runningman** [awsdocs/aws-cloudformation-user-guide#712]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizerid

The documentation states:
If you specify this property, specify CUSTOM for the AuthorizationType property.

But if you have a Cognito authorizer then COGNITO_USER_POOLS is also a valid AuthorizationType

**Comment by mcdwil** [comment]
Good catch! Merged #713
