### ISSUE TITLE
AWS::Cognito::UserPoolClient GetAtt values are not supported

### ISSUE THREAD

**Issue by xRokco** [awsdocs/aws-cloudformation-user-guide#72]
On the AWS::Cognito::UserPoolClient page [1] it lists available return values for the GetAtt function as ClientSecret and Name. Neither of these values work, though.

When !GetAtt 'UserPoolClient.Name' is added to the Outputs section of a template it just returns "Name attribute not supported at this time, please use the CLI or Console to retrieve this value" as the value. Same thing for ClientSecret.

I believe the docs should be updated to remove these unsupported GetAtt calls.

[1]: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html

**Comment by ckesser** [comment]
Thanks for bringing this to our attention! The Fn::GetAtt return values have been removed from the docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolclient.html#w2ab2c21c10d292c11. Closing this issue.

**Comment by cruizba** [comment]
A little question: Why there's no Fn::GetAtt return values?

**Comment by misterjoshua** [comment]
> A little question: Why there's no Fn::GetAtt return values?

I'm curious about this too. It doesn't seem clear how one can create an AWS::Cognito::UserPoolClient and use it in the same CloudFormation template.

**Comment by cruizba** [comment]
> I'm curious about this too. It doesn't seem clear how one can create an AWS::Cognito::UserPoolClient and use it in the same CloudFormation template.

Basically is not possible. The unique information you can obtain from the resource is the client id, by doing a `!Ref` to the resource. Is a bit difficult to configure an application...
