### ISSUE TITLE
"AwsvpcConfiguration" or "AwsVpcConfiguration"?

### ISSUE THREAD

**Issue by davewongb6** [awsdocs/aws-cloudformation-user-guide#726]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-networkconfiguration.html

When using NetworkConfiguration in EcsParameters for AWS::Events::Rule Targets, "AwsVpcConfiguration" should be used. But for AWS::ECS::Service properties, "AwsvpcConfiguration" should be used.

**Comment by PatMyron** [comment]
[`AWS::ECS::Service.NetworkConfiguration.AwsVpcConfiguration`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-service-networkconfiguration.html#cfn-ecs-service-networkconfiguration-awsvpcconfiguration) capitalization being discussed here as well:

https://github.com/aws-cloudformation/cfn-python-lint/issues/1706

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
