### ISSUE TITLE
AWS::Cognito::UserPool. unable to require MFA using only TOTP method

### ISSUE THREAD

**Issue by yashutanna** [awsdocs/aws-cloudformation-user-guide#73]
Hi

I dont know if i am posting this on the correct forum - but I'm hoping someone here can guide me to the right direction.

As far as the documentation goes for setting up a Cognito UserPool using the AWS::Cognito::UserPool Type - there is nowhere to configure the UserPool to Require MFA using only the TOTP method

When setting the MfaConfiguration attribute to "ON" - cloudformation errors out with a message to the sound of SMSconfiguration and Phone number verification is required when MFAConfiguration is set to ON or OPTIONAL

I would like to enable MFA using only TOTP method.

PS: This is possible by using the Web console

Thanks

**Comment by cmmeyer** [comment]
Hey there!

The Cognito team has not yet added this option for CloudFormation, which is why you aren't seeing it documented.  I just reached out to the Cognito team to see if they have any timeframe for support, and to let them know there's an open issue here with +10 👍

**Comment by arnagarjun** [comment]
Any updates on this?

**Comment by excavador** [comment]
Any updates?

**Comment by EricHislop** [comment]
@cmmeyer Any update?

**Comment by sbonasu** [comment]
+1

**Comment by cristianketrics** [comment]
+1

**Comment by excavador** [comment]
Any updates?

**Comment by sodaru-it** [comment]
+100

**Comment by vimalpatnaik** [comment]
+1

**Comment by LorneCurrie** [comment]
Any update on this?

**Comment by bensie** [comment]
Looks like support for "EnabledMfas" was quietly added at some point 🎉 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-enabledmfas
