### ISSUE TITLE
Broken Source Code for cfn-response Module

### ISSUE THREAD

**Issue by akshayj8899** [awsdocs/aws-cloudformation-user-guide#735]
The source code available at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html for the cfn-response module for Python 2 and 3 is broken out of the box. Both scripts import "requests" from "botocore.vendored". However, in March 2020 the requests library in Botocore has become deprecated (https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/). This causes the code to fail to run successfully. The change is to "import requests" directly.

**Comment by rachfop** [comment]
Hello, thank you for your suggestion. I have created a ticket about the template effected. For more information about botocore see [here](https://github.com/boto/botocore/pull/1829).
