### ISSUE TITLE
AWS::ECS::TaskDefinition Volume Documentation Missing EFS Volume Configuration Options

### ISSUE THREAD

**Issue by iamderrick** [awsdocs/aws-cloudformation-user-guide#737]
[awsdocks/aws-cloudformation-user-guide/doc_source/aws-properties-ecs-taskdefinition-volumes.md](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-ecs-taskdefinition-volumes.md) does not document the "efsVolumeConfiguration" property. I believe the full breakdown of possible properties looks like this:

```
"efsVolumeConfiguration": {
    "transitEncryptionPort": null,
    "fileSystemId": null,
    "authorizationConfig": {
        "iam": null,
        "accessPointId": null
    },
    "transitEncryption": null,
    "rootDirectory": null
}
```

**Comment by joelbrandenburg** [comment]
My understanding is that we currently don't support specifying an efsVolumeConfiguration in a CloudFormation template.  Until this feature is supported within CloudFormation, you would need to use the API or CLI to do this.
