### ISSUE TITLE
`AWS::SecretsManager::RotationSchedule` RDS examples missing required parameters

### ISSUE THREAD

**Issue by hauntingEcho** [awsdocs/aws-cloudformation-user-guide#741]
The [RDS examples for RotationSchedule](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-secretsmanager-rotationschedule.md#yaml-1) are missing the parameters `host` and `engine` which are [required for the rotation function that they're using](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_available-rotation-templates.html#sar-template-mysql-singleuser).

Attempting to add the host via the database's `Endpoint.Address` attribute results in a circular dependency.

**Comment by hauntingEcho** [comment]
It seems like resolving this may require another way to pass host/port information to that lambda, rather than in the same secret.

**Comment by rachfop** [comment]
Thank you for your suggestion. The Host parameter does not need to be added to the template because SecretTargetAttachment will generate it in the secret.

**Comment by hauntingEcho** [comment]
Thanks!  Where can we find documentation on what SecretTargetAttachment changes in the target secret?
