### ISSUE TITLE
Update requires specification for AWS::Redshift::Cluster

### ISSUE THREAD

**Issue by JohnZProd** [awsdocs/aws-cloudformation-user-guide#744]
Update requires specification for AWS::Redshift::Cluster

Hi, 

According to the documentation for AWS::Redshift::Cluster, an update of the NodeType and NumberOfNodes properties are classified as 'No interruption'.

```
Type: AWS::Redshift::Cluster
Properties: 
  ...
  NodeType: String
  NumberOfNodes: Integer
  ...
```

https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-redshift-cluster.md

However, according to the documentation for Redshift resizing [1], updating the NodeType of a cluster will perform a classic resize, where only reads will be allowed for a period of time (~30 min in my test environment)

Furthermore, updating the NumberOfNodes will perform an Elastic resize (~5 min in my test environment), during which the cluster will be unavailable.

Could we edit the NodeType and NumberOfNodes property on this resource such that the update type is 'Some interruption'

Thanks,

John

[1] https://aws.amazon.com/premiumsupport/knowledge-center/resize-redshift-cluster/

**Comment by rachfop** [comment]
Hello, thank you for your submission. Every piece of feedback we receive helps. The "Type", "Required", and "Update behavior" fields for each property are auto-generated from the [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). I've submitted a ticket to correct this value in the resource spec. The [source documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html) will be updated after the specification is updated.
