### ISSUE TITLE
document hosted transforms

### ISSUE THREAD

**Issue by hauntingEcho** [awsdocs/aws-cloudformation-user-guide#761]
the transform "AWS::SecretsManager-2020-07-23" is used in the examples here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-rotationschedule.html#aws-resource-secretsmanager-rotationschedule--examples

but is not documented alongside the other transformations: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-serverless.html

**Comment by PatMyron** [comment]
[`AWS::SecretsManager` transform documented now](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-aws-secretsmanager.html)

but [`AWS::CodeDeployBlueGreen`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/blue-green.html) and `AWS::CodeStar` seem missing from that section:
https://forums.aws.amazon.com/thread.jspa?threadID=255716
https://stackoverflow.com/questions/54607731/how-to-customize-aws-codestar-cloudformation-template-to-create-specific-codeb
https://stackoverflow.com/questions/43591128/change-iam-role-for-a-lambda-in-a-cloudformation-template-in-a-codestar-project
https://stackoverflow.com/questions/60104575/customizing-a-prod-deployment-from-a-codestar-project

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
