### ISSUE TITLE
inconsistent Type for Parameters property between AWS::RDS::DBClusterParameterGroup and AWS::RDS::DBParameterGroup

### ISSUE THREAD

**Issue by rhbecker** [awsdocs/aws-cloudformation-user-guide#774]
For [AWS::RDS::DBClusterParameterGroup](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-rds-dbclusterparametergroup.md), the `Parameters` property **Type** is listed as **Json**.

For [AWS::RDS::DBParameterGroup](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-rds-dbparametergroup.md), the `Parameters` property **Type** is listed as **Map of String**.

Based on the provided examples on each page, **Map of String** seems more accurate for both cases. Can you explain why you've chosen **Json** for the former?

**Comment by ajmay-aws** [comment]
The property type information is pulled automatically from the public resource spec (which you can see here: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json). 
In the resource spec, AWS::RDS::DBClusterParameterGroup.Parameters is defined as Json, whereas AWS::RDS::DBParameterGroup.Parameters is defined as a map of string types.

**Comment by rhbecker** [comment]
Thanks, @ajmay-aws, that's useful to understand the connection between the documentation and the public resource spec.

What I'm hoping to better understand is why they'd be specified to require different types when the example values provided seem to be the same type as one another. From a user perspective, what are the implications of Type being Json versus Map of String?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
