### ISSUE TITLE
inconsistent Update Behavior for DynamoDB SSESpecification

### ISSUE THREAD

**Issue by miparnisari** [awsdocs/aws-cloudformation-user-guide#780]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#aws-resource-dynamodb-table-properties

![image](https://user-images.githubusercontent.com/5374887/92529945-4b81fd80-f1e0-11ea-8a68-ce42b864b75f.png)

**Comment by rachfop** [comment]
Thank you for your contribution. I have made the updates to the docs and it should appear shortly.
