### ISSUE TITLE
quickref-elasticbeanstalk.md doesn't run out of the box

### ISSUE THREAD

**Issue by tommym9** [awsdocs/aws-cloudformation-user-guide#782]
Hi,

I created a stack using the template in `quickref-elasticbeanstalk.md` to test where my template is going wrong and noticed this template fails with the same error as my template:

`Environment failed to launch as it entered Terminated state` for the `sampleEnvironment`. The status is CREATE_FAILED.

Just a heads up that this could do with updating as trying to debug against a broken version is really difficult for beginners like me.

Cheers

Tom

**Comment by rachfop** [comment]
Thank you for your request. Did you replace solution-stack with a solution stack name (platform version)?
I'll add it to the team's list of items for future consideration and then close this issue.
