### ISSUE TITLE
AWS::Cognito::UserPool.CaseSensitive is required

### ISSUE THREAD

**Issue by xrn** [awsdocs/aws-cloudformation-user-guide#797]
Template
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "myCognito": {
      "Properties": {
        "UsernameConfiguration": {}
      },
      "Type": "AWS::Cognito::UserPool"
    }
  }
}
```

Error
```
Value null at 'usernameConfiguration.caseSensitive' failed to satisfy constraint
```

Current documentation https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html

Looks like CaseSensitive is required

**Comment by xrn** [comment]
@prazmaap what do you think here?

**Comment by douglas-gibbons-lark** [comment]
@prazmaap do you want me to create a PR for you?

**Comment by rachfop** [comment]
Our tools auto-generate the "_Required_", "_Type_", "and "_Update requires_" fields for each property from the [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). 
I submitted a ticket to correct this value. We will refresh the [documentation ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html)after the specification update.

**Comment by xrn** [comment]
@rachfop seems that this is still not requried - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html
