### ISSUE TITLE
Required should be Conditional for config objects in AWS::AppSync::DataSource

### ISSUE THREAD

**Issue by aniruddhawani** [awsdocs/aws-cloudformation-user-guide#805]
I was looking at LambdaConfig specifically and it mentions that it needs to be a valid ARN but the required value is set to 'No'.

- If the lambda ARN needs to be in valid format only and the ARN doesn't need to exist at the time of creating the appsync datasource, then LambdaConfig description should be updated to 'valid ARN format'
- If the lambda ARN needs to be in valid format and the ARN needs to exist at the time of creating the appsync datasource, then LambdaConfig Required value should be updated to Conditional

Similar logic can be applied to other configs as well (e.g. DynamoDBConfig, ElasticsearchConfig, RelationalDatabaseConfig)

Source: https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-resource-appsync-datasource.md

**Comment by aniruddhawani** [comment]
After testing, it seems that the ARN doesn't need to exist. It just needs to be a valid ARN format.

If that's right, LambdaConfig description should be updated to 'valid ARN format' for better clarity.

**Comment by KristinaPeterson** [comment]
Thank you for your feedback. I am researching the issue you reported and will provide you with updates here.

**Comment by KristinaPeterson** [comment]
Thank you again for calling our attention to this issue. I did some research and to support cross-account access, the ARN does not need to exist in the current account. It could be an ARN in another account. As you suggested, I am updating the documentation for AWS::AppSync::DataSource.LambdaConfig to incorporate this information for better clarity.
