### ISSUE TITLE
AWS::ECR::Repository.RepositoryPolicyText and AWS::KMS::Key.KeyPolicy are missing Type field

### ISSUE THREAD

**Issue by ibrt** [awsdocs/aws-cloudformation-user-guide#811]
As per title. Found this because it is breaking the goformation schema update scripts: https://github.com/awslabs/goformation/issues/313

**Comment by ibrt** [comment]
At https://github.com/awsdocs/aws-cloudformation-user-guide/blob/b2a0d986f7839377003f72d80a2cd35218067ae8/doc_source/aws-resource-ecr-repository.md:

```
{
  "Type" : "AWS::ECR::Repository",
  "Properties" : {
      "[ImageScanningConfiguration](#cfn-ecr-repository-imagescanningconfiguration)" : Json,
      "[ImageTagMutability](#cfn-ecr-repository-imagetagmutability)" : String,
      "[LifecyclePolicy](#cfn-ecr-repository-lifecyclepolicy)" : LifecyclePolicy,
      "[RepositoryName](#cfn-ecr-repository-repositoryname)" : String,
      "[RepositoryPolicyText](#cfn-ecr-repository-repositorypolicytext)" : , <-- Empty type
      "[Tags](#cfn-ecr-repository-tags)" : [ [Tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html), ... ]
    }
}
```

And at https://github.com/awsdocs/aws-cloudformation-user-guide/blob/b2a0d986f7839377003f72d80a2cd35218067ae8/doc_source/aws-resource-kms-key.md:

```
{
  "Type" : "AWS::KMS::Key",
  "Properties" : {
      "[Description](#cfn-kms-key-description)" : String,
      "[Enabled](#cfn-kms-key-enabled)" : Boolean,
      "[EnableKeyRotation](#cfn-kms-key-enablekeyrotation)" : Boolean,
      "[KeyPolicy](#cfn-kms-key-keypolicy)" : , <-- Empty type
      "[KeyUsage](#cfn-kms-key-keyusage)" : String,
      "[PendingWindowInDays](#cfn-kms-key-pendingwindowindays)" : Integer,
      "[Tags](#cfn-kms-key-tags)" : [ [Tag](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html), ... ]
    }
```

**Comment by rachfop** [comment]
@ibrt thank you for your feedback. We are working with our team to resolve this issue. There is a little bit more traction on [this thread](https://github.com/awslabs/goformation/issues/300#issuecomment-706670928), that you might be interested in as well.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
