### ISSUE TITLE
Template Constraint Rules not mentioned in Template Anatomy

### ISSUE THREAD

**Issue by dontirun** [awsdocs/aws-cloudformation-user-guide#816]
CloudFormation has the feature to make Rules / Assertions in templates as described here
https://docs.aws.amazon.com/servicecatalog/latest/adminguide/reference-template_constraint_rules.html

This should be in the Template Anatomy Guide

**Comment by rachfop** [comment]
Related: https://github.com/awsdocs/aws-cloudformation-user-guide/issues/794

Thank you for your suggestion. We are currently investigating.

**Comment by PatMyron** [comment]
closing as duplicate of https://github.com/awsdocs/aws-cloudformation-user-guide/issues/794
