### ISSUE TITLE
AWS::Glue::Connection ConnectionType is missing some valid options

### ISSUE THREAD

**Issue by jonsnowseven** [awsdocs/aws-cloudformation-user-guide#818]
Hello.

In [AWS::Glue::Connection ConnectionInput](https://github.com/awsdocs/aws-cloudformation-user-guide/blob/master/doc_source/aws-properties-glue-connection-connectioninput.md), there are some options missing in **ConnectionType**, e.g., `NETWORK`. This option is valid since I tested it with CloudFormation. Do not know about any other missing options.

```md
...
`ConnectionType`  <a name="cfn-glue-connection-connectioninput-connectiontype"></a>
The type of the connection\. Currently, these types are supported:  
+  `JDBC` \- Designates a connection to a database through Java Database Connectivity \(JDBC\)\.
+  `KAFKA` \- Designates a connection to an Apache Kafka streaming platform\.
+  `MONGODB` \- Designates a connection to a MongoDB document database\.
<---- SOME MISSING OPTIONS LIKE NETWORK
SFTP is not supported\.  
*Required*: Yes  
*Type*: String  
*Update requires*: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
...
```

Thank you in advance.

**Comment by rachfop** [comment]
Hello, thank you for your suggestion. The docs have been updated here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-glue-connection-connectioninput.html
