### ISSUE TITLE
AWS::ECS::TaskDefinition.EFSVolumeConfiguration.AuthorizationConfig has invalid type

### ISSUE THREAD

**Issue by PaulMaddox** [awsdocs/aws-cloudformation-user-guide#829]
In the CloudFormation Resource Specification, the following property is defined as having two types:

`AWS::ECS::TaskDefinition.EFSVolumeConfiguration.AuthorizationConfig`

```
        "AuthorizationConfig": {
          "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ecs-taskdefinition-efsvolumeconfiguration.html#cfn-ecs-taskdefinition-efsvolumeconfiguration-authorizationconfig",
          "UpdateType": "Immutable",
          "Required": false,
          "PrimitiveType": "Json",
          "Type": "AuthorizationConfig"
        }
```

This is not valid, and it should not have a `PrimitiveType` defined as it already has a `Type`. 

This is causing issues with downstream libraries that depend on the AWS CloudFormation Resource Specification. 

See: https://github.com/awslabs/goformation/issues/327

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
