### ISSUE TITLE
AWS::Route53::PublicHostedZone references DelegationSetId element that doesn't (sadly) appear to actually exist

### ISSUE THREAD

**Issue by Pablissimo** [awsdocs/aws-cloudformation-user-guide#830]
On the [AWS::Route53::PublicHostedZone docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-hostedzone.html) the following text appears in the bulleted notes at the top of the page:

>If you want to use the same name servers for multiple public hosted zones, you can optionally associate a reusable delegation set with the hosted zone. See the DelegationSetId element.

However, `DelegationSetId` isn't subsequently mentioned in the document nor does it appear to actually be supported by CloudFormation.

**Comment by jtnz** [comment]
Appears to just be a [copy and paste](https://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateHostedZone.html) from the API docs that does support it. :disappointed:

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
