### ISSUE TITLE
Broken text in token signing docs for AWS IoT Core

### ISSUE THREAD

**Issue by timmattison** [awsdocs/aws-cloudformation-user-guide#835]
This page - https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-properties-iot-authorizer-tokensigningpublickeys.md - has some broken text that indicates the feature is not supported but it looks like two sentences are blended together.

Actual text:

```
The TokenSigningPublicKeys property type specifies Not currently supported by AWS CloudFormation. for an AWS::IoT::Authorizer.
```

Suggested text:

```
The TokenSigningPublicKeys property is not currently supported by AWS CloudFormation for an AWS::IoT::Authorizer.
```

**Comment by asavila** [comment]
Issue resolution published, should show up on public site in a few hours.
