### ISSUE TITLE
Typo at S3 IAM policy action

### ISSUE THREAD

**Issue by NikolaBravo** [awsdocs/aws-cloudformation-user-guide#84]
Link: https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-IAM.html#bulk-load-tutorial-IAM-add-role-cluster

Typo: This this policy grants s3::Get* and s3:List* permissions to all buckets.
Invalid: s3::Get* 
Valid: s3:Get*

**Comment by PatMyron** [comment]
Think this has been fixed

**Comment by ckesser** [comment]
@PatMyron's right, this does appear to have been fixed. Thanks for identifying this typo @NikolaBravo! Closing this issue.
