### ISSUE TITLE
User guide missing docs for AWS::SES::ContactList

### ISSUE THREAD

**Issue by michael-kiley-verified** [awsdocs/aws-cloudformation-user-guide#849]
The [release history](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) states that a resource called AWS::SES:ContactList was updated on November 5th, but it just links to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_SES.html, where there is no mention of this resource type. When I try to find documentation through the CLI by running `aws cloudformation describe-type --type-name AWS::SES::ContactList --type RESOURCE`, I get `An error occurred (TypeNotFoundException) when calling the DescribeType operation: The Resource Type 'AWS::SES::ContactList' cannot be found.`

**Comment by rachfop** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ses-contactlist.html is up and running again. Thank you for pointing that out.
