### ISSUE TITLE
DataBrew return values are not correct

### ISSUE THREAD

**Issue by sgulbetekin** [awsdocs/aws-cloudformation-user-guide#864]
Hi team, CFN Return Values for [Job](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-job.html#aws-resource-databrew-job-return-values), [Project](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-project.html#aws-resource-databrew-project-return-values), [Recipe](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-recipe.html#aws-resource-databrew-recipe-return-values) and [Schedule](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-schedule.html#aws-resource-databrew-schedule-return-values) are not correct, all of them reference to `{ "Ref": "myDataset" }` instead of their own Ref values. Probably it is a copy&paste issue from [DataSet](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-databrew-dataset.html#aws-resource-databrew-dataset-return-values), I could submit a PR in Github, however not sure what Ref values are there in each of them. If someone could have a look. Thanks

**Comment by overhere00** [comment]
This has now been fixed - thanks for letting us know.

-Mike C.
