### ISSUE TITLE
ValidationDomain of DomainValidationOptions of AWS::CertificateManager::Certificate not optional

### ISSUE THREAD

**Issue by dldinternet** [awsdocs/aws-cloudformation-user-guide#865]
1 validation error detected: Value null at 'domainValidationOptions.1.member.validationDomain' failed to satisfy constraint: Member must not be null (Service: AWSCertificateManager; Status Code: 400; Error Code: ValidationException; Request ID: 3bacf130-4060-42e1-a1c6-ee7fe95831ae; Proxy: null)

On this page: https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-properties-certificatemanager-certificate-domainvalidationoption.md
For Propertied.ValidationMethod == 'DNS' the DomainValidationOption is required and follows the similar requirements as for EMAIL ValidationMethod

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
