### ISSUE TITLE
Databrew.Action object not fully specified

### ISSUE THREAD

**Issue by pplu** [awsdocs/aws-cloudformation-user-guide#876]
Hi,

The `Parameters` parameter in the Databrew.Action object does not specify what data type it is. I've taken a look at the spec, and it is also missing the data type.

```
      "AWS::DataBrew::Recipe.Action" : {
         "Documentation" : "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-recipe-action.html",
         "Properties" : {
            "Operation" : {
               "Documentation" : "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-recipe-action.html#cfn-databrew-recipe-action-operation",
               "PrimitiveType" : "String",
               "Required" : true,
               "UpdateType" : "Mutable"
            },
            "Parameters" : {
               "Documentation" : "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-databrew-recipe-action.html#cfn-databrew-recipe-action-parameters",
               "Required" : false,
               "UpdateType" : "Mutable"
            }
         }
      },
```

**Comment by rachfop** [comment]
Our tools auto-generate the "Required", "Type", "and "Update requires" fields for each property from the [resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html). I submitted a ticket to correct this value. We will refresh the [documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html) after the specification update.
