### ISSUE TITLE
AWS Batch + Fargate documentation issues

### ISSUE THREAD

**Issue by pplu** [awsdocs/aws-cloudformation-user-guide#884]
I've written an article on getting AWS Batch with Fargate to provision from CloudFomation: https://github.com/pplu/cfn-fargate-batch

This article explains the situation with the CloudFormation documentation for this use case, which I think was the cause of all my problems.

**Comment by HLeeHart** [comment]
The full AWS CloudFormation support for using AWS Fargate resources in AWS Batch has not yet been released. Some resources specific to AWS Fargate resources are not yet in the AWS CloudFormation Resource Spec (e.g. FargatePlatformConfiguration). 

Our CloudFormation documentation process is automated and some of the Fargate descriptions for the existing resources and properties came through. The reference for the new-for-Fargate resources and properties (e.g. FargatePlatformConfiguration) will be available in the docs a little while after they are available in the Resource Spec.

I am closing this issue. Please feel free to open a new issue after the support is fully available in AWS CloudFormation if you're not able to make it work.

Thank you,

Lee Hart
Writer, AWS Batch

**Comment by pplu** [comment]
> Our CloudFormation documentation process is automated and some of the Fargate descriptions for the existing resources and properties came through

Some of the properties are incorrect (VCPU and MEMORY settings), and one is missing. **everything** except one property is documented making it look like it is supported, so this is more than "some" of the properties.

> Please feel free to open a new issue after the support is fully available in AWS CloudFormation if you're not able to make it work.

When will the correct documentation be fully available?

If you read the article, I already **did** make it work. So I would urge you to publish the correct spec and documentation in as short time as possible. The current state of documentation is badly misleading your customers, and making them waist their time. Your customers shouldn't have to go through the same experience as me.

**Comment by pplu** [comment]
BTW: I wouldn't close this issue, as at least it may help others know whats going on

**Comment by HLeeHart** [comment]
> Some of the properties are incorrect (VCPU and MEMORY settings)

Can you provide more details? [memory](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-memory) and [Vcpu](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties.html#cfn-batch-jobdefinition-containerproperties-vcpus) parameters are documented as not supported for Fargate but to use [ResourceRequirement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-resourcerequirement.html) instead.

> one is missing

Both FargatePlatformConfiguration and NetworkConfiguration resource types are missing, and numerous properties are missing.

> When will the correct documentation be fully available?

The full documentation will be fully available within a day or so of the Resource Spec being updated. I'm not part of the team that updates the Resource Spec and I don't know what they have announced so I can't comment on when that will be. This affects all services that had features added at re:Invent.

> Your customers shouldn't have to go through the same experience as me.

I agree. Before I have any other major service update that touches so many existing pages, I will see what I can do to minimize the changes to the CloudFormation docs before the CloudFormation support is released. It's not something I've hit before.

I will leave this issue open until the docs are updated. I will close it at that time.

**Comment by pplu** [comment]
> Can you provide more details? memory and Vcpu parameters are documented as not supported for Fargate but to use ResourceRequirement instead.

The values for MEMORY in the [ResourceRequirement](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-resourcerequirement.html) Property don't work as the documentation says. I found out I had to use `512`, `1024`, etc (inspired by the values that were in the [product launch](https://aws.amazon.com/blogs/aws/new-fully-serverless-batch-computing-with-aws-batch-support-for-aws-fargate/)), when the documentation states using `0.5`, `1`, etc. When you use the documented values, you get errors.

> It's not something I've hit before.

That's why I thought it was more of a documentation error, than some information that leaked previous official support. Everything seemed in place, so trying hard I got it to work imagining that some property was not documented by error.

**Comment by HLeeHart** [comment]
The MEMORY values have been updated in the MEMORY and VCPU docs under ResourceRequirement. Thank you.

**Comment by HLeeHart** [comment]
The remainder of the AWS Cloudformation docs for AWS Batch using AWS Fargate resources have now been published. For example, here's the NetworkingConfiguration property type.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-jobdefinition-containerproperties-networkconfiguration.html
Thank you for your patience.
