### ISSUE TITLE
Add documentation for Lambda Containers

### ISSUE THREAD

**Issue by binoculars** [awsdocs/aws-cloudformation-user-guide#889]
https://github.com/awsdocs/aws-cloudformation-user-guide/blob/main/doc_source/aws-resource-lambda-function.md

Should include:
- PackageType: Image
- Code.ImageUri: `<ECR URI within the same account>`

**Comment by devlinbd2** [comment]
CloudFormation user guide was finally published to the web site on Dec 20th. Usually, there is a lag time of a few days before the GitHub version is also updated.
