### ISSUE TITLE
AWS::SSM::MaintenanceWindow - CutOff max/min values are incorrect?

### ISSUE THREAD

**Issue by j0nathontayl0r** [awsdocs/aws-cloudformation-user-guide#891]
Existing min/max values for AWS::SSM::MaintenanceWindow are referenced here [SSM Maintainence Window CloudFormation Documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-maintenancewindow.html#cfn-ssm-maintenancewindow-name  ). Currently this page advises `Cuttoff` has a min/max value of:
 
* Minimum: 0
* Maximum: 23

I'm not sure if this is correct. When attempting to run with a value of 12 for Cuttoff in CloudFormation I receive the error:

```Cuttoff was 12 but must be smaller than 5 (Duration - 1 ) (Service: AmazonSSM; Status Code: 400; Error Code: ValidationException; Request ID: 269f8746-aa7f-46ca-9a60-10e875a538bd)```

Should the max value in the CloudFormation documents instead be 4 (< 5)?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
