### ISSUE TITLE
S3 Bucket CloudFormation ReplicationConfiguration

### ISSUE THREAD

**Issue by jsoncow** [awsdocs/aws-cloudformation-user-guide#921]
Hi

Reading this page on Replication Configuration, I see "Amazon S3 can store replicated objects in only one destination bucket." under replication configuration under properties.  

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-replicationconfiguration 

However, testing and reading this launch seems to indicate otherwise: https://aws.amazon.com/blogs/aws/new-amazon-s3-replication-adds-support-for-multiple-destination-buckets/#:~:text=S3%20Replication%20(multi%2Ddestination)%20is%20available%20today%20in%20all,destination)%20applies%20for%20each%20rule Where I could have multiple destination buckets.

Thanks!

**Comment by sasake615** [comment]
Thank you for telling us about this issue and for your pull request. A member of the team will review it and will provide updates here about progress.

**Comment by sasake615** [comment]
Thank you for taking the time to submit feedback on our documentation! We updated the S3 CFN [ReplicationConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-replicationconfiguration) description as you suggested. We are always working to improve documentation, and your feedback helps us know where to focus our efforts. Best regards.
