### ISSUE TITLE
Missing pattern in AWS::Chatbot::SlackChannelConfiguration property

### ISSUE THREAD

**Issue by jotanavarro** [awsdocs/aws-cloudformation-user-guide#925]
The property `ConfigurationName` is defined simply as a `String` type.  It is not, there is some pattern that it is matched while deploying the resource, giving a somewhat cryptic message when this pattern is not honoured:

```
Properties validation failed for resource FooChatbot with message: #/ConfigurationName: failed validation constraint for keyword [pattern]
```

In my case the value for the property contained spaces, as in "The Chatbot used for FOO service".  It was deployed without any error when the value was changed to `FooServiceChatbot`.

I believe the pattern that is required should be specified [in the documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-chatbot-slackchannelconfiguration.html).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
