### ISSUE TITLE
Documentation for AWS::ElastiCache::User states that Property Engine string should be 'Redis' when it should be 'redis'

### ISSUE THREAD

**Issue by its-mirus-lu** [awsdocs/aws-cloudformation-user-guide#928]
**Problem** When 'Redis' is provided as a value for AWS::ElastiCache::User Engine, CloudFormation returns an error message as follows:

```
Properties validation failed for resource <resource_name>
532B with message:
#/Engine: #: only 1 subschema matches out of 2
#/Engine: failed validation constraint for keyword [enum]
```

The documentation for AWS::ElastiCache::User states that for Property.Engine:
```The current supported value is Redis.```
[AWS::Elasticache::User Engine](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-user.html#cfn-elasticache-user-engine)

**Solution** Using all lowercase 'redis' solves the issue. This also matches the lower-case 'redis' shown in the console (see attachment)

**Recommendation** Modify documentation to reflect that 'redis' (all lowecase) must be provided as value

![lowercase_redis](https://user-images.githubusercontent.com/48691662/108106198-78b1c200-7042-11eb-9e86-b61d06a9fbdc.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
