### ISSUE TITLE
AWS::SNS::TopicPolicy Silently accepts invalid policies

### ISSUE THREAD

**Issue by jaferrando** [awsdocs/aws-cloudformation-user-guide#93]
Test Policy:

{
	"Version": "2008-10-17",
	 "Statement": [
	  {
	     "Effect": "Allow",
             "Action":"sns:Publish"
	     "Principal": {
	       "AWS": "1234567689012",
	       "AWS": "2345676890123"
	     }
	 ]
}

Expected behaviour: validation error.
Obtained behaviour: SNS topic remains with an empty policy

**Comment by mig281** [comment]
@jaferrando Researching the issue with the service team.

**Comment by mig281** [comment]
@jaferrando We weren't able to reproduce it. If you see this happen again, please file a ticket with AWS Customer Support.
