### ISSUE TITLE
Cannot add custom AWS::Cognito::UserPool SchemaAttribute with name same as standard attribute

### ISSUE THREAD

**Issue by Guneetgstar** [awsdocs/aws-cloudformation-user-guide#932]
# Description

While adding a e.g. `custom:sub` attribute via console or CLI is a simple task, the same cannot be done via a `CloudFormation` template.

# Code

```
{
  "Type": "AWS::Cognito::UserPool",
  "Properties": {
.
.
.
"Schema": [
      {
        "Name": "custom:sub",
        "AttributeDataType": "String",
        "DeveloperOnlyAttribute": false,
        "Mutable": true
      },
     {
        "Name": "sub",
        "AttributeDataType": "String",
        "DeveloperOnlyAttribute": false,
        "Mutable": true
      }
    ]
}
```

# Result

Custom attribute created with name `custom:custom:sub`

# Expected

Custom attribute created with name `custom:sub`

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
