### ISSUE TITLE
Discrepancy between the allowed values and the actually given examples for MySQL RDS Engine parameter

### ISSUE THREAD

**Issue by turnopil** [awsdocs/aws-cloudformation-user-guide#955]
In the documentation, there is a discrepancy between the allowed values and the actually given examples. 
And this can cause a problem when updating the CFN stack. Because the values of the Engine parameter `MySQL` and `mysql` for CFN are different and when you set first and then tries to use second this leads to a replacement of DB instance during the update.

Hence, the documentation needs to be changed to ensure that the `mysql` "Engine" property doesn't contain any Upper case characters.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
