### ISSUE TITLE
Confusing documentation for ElasticIP Tags property

### ISSUE THREAD

**Issue by pplu** [awsdocs/aws-cloudformation-user-guide#959]
Hi,

The documentation for the ElasticIP Tags property is confusing: https://docs.aws.amazon.com/es_es/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-eip.html#cfn-ec2-eip-tags

It states:
> Update requires: No interruption

and

> Updates to the Tags property may require some interruptions. Updates on an EIP reassociates the address on its associated resource.

Reading this, I don't know what to expect from CloudFormation

**Comment by rachfop** [comment]
Hey @pplu, the `Update requires: No interruption` is automatically generated from the Resource Specification file. I believe the note for the Tags property is correcting the `Update requires:`, meaning that the Tags property may require some interruptions. We will try to get resource spec updated to be more accurate. Thanks for you feedback.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the "awsdocs" org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
