### ISSUE TITLE
Warming pools in AWS::AutoScaling::AutoScalingGroup

### ISSUE THREAD

**Issue by nitrocode** [awsdocs/aws-cloudformation-user-guide#961]
How does one add asg warm pools in cloud formation?

The api and awscli support it but the cf docs haven't updated yet. 

Edit: I see now at the bottom of the blog post

> AWS CloudFormation support for Warm Pools will be coming soon

**Comment by rachfop** [comment]
Thank you for your feedback! If you're talking about [this blog post](https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-ec2-auto-scaling-introduces-warm-pools-accelerate-scale-out-while-saving-money/) then yes, as of today it states:
> AWS CloudFormation support for Warm Pools will be coming soon
