### ISSUE TITLE
AWS::MediaLive::Input ref result description is incorrect

### ISSUE THREAD

**Issue by starpebble** [awsdocs/aws-cloudformation-user-guide#983]
Please accept my pull request.  The description of the Ref function output for an AWS::MediaLive::Input is incorrect.  It's mistakenly described as the name.  The correct description is it is the id.  I fixed this in my pull request.  

Pull Request:
https://github.com/awsdocs/aws-cloudformation-user-guide/pull/982

 Please accept my request.  I'd like to see what's it is like to change AWS documentation quickly on github.

**Comment by starpebble** [comment]
@rachfop Hi.  Nice to meet you.  What does it take to get a pull request accepted to this repository? My change is tiny, exactly one line.

**Comment by rachfop** [comment]
Thank you for your feedback! I have merged your changes. Thank you helping us update the docs.
