### ISSUE TITLE
Ref value from AWS::RDS::DBCluster UPPERCASE

### ISSUE THREAD

**Issue by biohazd** [awsdocs/aws-cloudformation-user-guide#994]
Is the !Ref Value from "AWS::RDS::DBCluster" really UPPERCASE?

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#aws-resource-rds-dbcluster-return-values

**Ref**
When you pass the logical ID of this resource to the intrinsic Ref function, 
Ref returns the name of the **DB cluster as an uppercase string**. 

If I use an Output, the value is all lowercase. If I view it in Clodufomation in the aWS console, it shows as all lowercase.

**Comment by randyurbano** [comment]
Thanks for your feedback. I confirmed that the value is returned in lowercase, and I updated the documentation.
